// Traditional Chinese glossary for hard vocabulary used across module content.
// Tap-to-reveal, Duolingo-style — see GlossaryText.jsx for the rendering component.
window.App = window.App || {};
window.App.Content = window.App.Content || {};

(function () {
  window.App.Content.GLOSSARY = {
    exhausted: { zh: "精疲力盡" },
    expedition: { zh: "遠征；探險" },
    thrilled: { zh: "非常興奮" },
    renewable: { zh: "可再生的" },
    migrate: { zh: "遷徙" },
    permanently: { zh: "永久地" },
    historians: { zh: "歷史學家" },
    historian: { zh: "歷史學家" },
    concessions: { zh: "讓步" },
    concession: { zh: "讓步" },
    recital: { zh: "獨奏會" },
    erupt: { zh: "噴發" },
    trekked: { zh: "跋涉" },
    trek: { zh: "跋涉" },
    denser: { zh: "更濃密的" },
    dense: { zh: "濃密的" },
    inference: { zh: "推論" },
    descriptive: { zh: "描述性的" },
    overjoyed: { zh: "欣喜若狂" },
    creativity: { zh: "創造力" },
    stranded: { zh: "受困；擱淺" },
    howling: { zh: "呼嘯（風聲）" },
    manuscript: { zh: "手稿" },
    renovation: { zh: "翻新；裝修" },
    vanished: { zh: "消失了" },
    mysteriously: { zh: "神秘地" },
    mysterious: { zh: "神秘的" },
    deforestation: { zh: "森林砍伐" },
    accelerated: { zh: "加速了" },
    conservationists: { zh: "環保人士" },
    incentives: { zh: "誘因；獎勵" },
    incentive: { zh: "誘因；獎勵" },
    obsolescence: { zh: "過時；淘汰" },
    artificially: { zh: "人為地" },
    anxiously: { zh: "焦慮地" },
    reassurances: { zh: "保證" },
    reassurance: { zh: "保證" },
    merger: { zh: "合併" },
    persevered: { zh: "堅持不懈" },
    persevere: { zh: "堅持不懈" },
    fascinated: { zh: "著迷" },
    effective: { zh: "有效的" },
    particularly: { zh: "特別地" },
    comfortable: { zh: "舒適的" },
    necessary: { zh: "必要的" },
    entrepreneur: { zh: "企業家" },
    phenomenon: { zh: "現象" },
    unnecessary: { zh: "不必要的" },
    volcano: { zh: "火山" },
    ecosystem: { zh: "生態系統" },
    ecosystems: { zh: "生態系統" },
    compromise: { zh: "妥協" },
    clarity: { zh: "清晰" },
    patience: { zh: "耐心" },
    genuine: { zh: "真正的；真實的" },
  };
})();
