// Grammar → "Past Simple Steps": the Past Simple tense broken into 11 short
// sub-levels, each with a Learn card shown before practice starts.
//   1-4  regular verbs (+ed, +d, doubling, y→ied)
//   5-9  irregular verbs in five groups
//   10   did / didn't + base verb (questions and negatives)
//   11   editing — find and fix the mistake
// These levels are the same for every difficulty tier (the rules themselves
// are the level), so GrammarModule does not filter them by tier.
//
// Item format matches GRAMMAR_ITEMS (fillblank / mc, correctIndex 0 — the
// options get shuffled at runtime by useShuffledQuestion). Each explanation
// gives the rule plus a second example that is not in the item itself.
window.App = window.App || {};
window.App.Content = window.App.Content || {};

(function () {
  window.App.Content.GRAMMAR_PAST_SIMPLE = [
    {
      id: "ps-1",
      emoji: "➕",
      title: "Regular verbs: add -ed",
      blurb: "walk → walked, play → played",
      learn: {
        intro:
          "We use the Past Simple for things that are finished, like yesterday, last week, or two days ago. For most regular verbs, just add -ed to the end of the verb.",
        headers: ["Now", "Past"],
        rows: [
          ["walk", "walked"],
          ["play", "played"],
          ["jump", "jumped"],
          ["help", "helped"],
          ["watch", "watched"],
          ["visit", "visited"],
        ],
        tips: [
          "The form is the same for every person: I walked, she walked, they walked. There is no -s in the Past Simple.",
          "Time clues: yesterday, last night, last week, two days ago, in 2020.",
        ],
        mistake: "Don't say \"She walks to school yesterday.\" Yesterday is finished, so say \"She walked to school yesterday.\"",
      },
      items: [
        { id: "ps1-1", type: "fillblank", sentence: "Yesterday, I ___ my grandma after school.", options: ["visited", "visit", "visits", "visiting"], correctIndex: 0, explanation: "\"Yesterday\" is finished, so the verb needs the Past Simple. Regular verbs add -ed: visit → visited. For example: \"We visited the zoo last month.\"" },
        { id: "ps1-2", type: "fillblank", sentence: "The children ___ in the park last Sunday.", options: ["played", "play", "plays", "playing"], correctIndex: 0, explanation: "\"Last Sunday\" is a finished time, so add -ed: play → played. For example: \"They played chess after lunch.\"" },
        { id: "ps1-3", type: "fillblank", sentence: "She ___ the door and walked into the classroom.", options: ["opened", "open", "opens", "opening"], correctIndex: 0, explanation: "The story is about something that already happened, so we use the Past Simple: open → opened. For example: \"He opened the box slowly.\"" },
        { id: "ps1-4", type: "fillblank", sentence: "We ___ for the bus for ten minutes this morning.", options: ["waited", "wait", "waits", "waiting"], correctIndex: 0, explanation: "\"This morning\" is over, so the verb is in the Past Simple: wait → waited. For example: \"I waited outside the shop.\"" },
        { id: "ps1-5", type: "fillblank", sentence: "He ___ his teacher a question in class yesterday.", options: ["asked", "ask", "asks", "asking"], correctIndex: 0, explanation: "Add -ed to a regular verb for a finished action: ask → asked. For example: \"She asked for some water.\"" },
        { id: "ps1-6", type: "fillblank", sentence: "My dad ___ the dishes after dinner last night.", options: ["washed", "wash", "washes", "washing"], correctIndex: 0, explanation: "\"Last night\" is finished, so use -ed: wash → washed. For example: \"Mum washed the car on Sunday.\"" },
        { id: "ps1-7", type: "fillblank", sentence: "The boy ___ the ball over the fence.", options: ["kicked", "kick", "kicks", "kicking"], correctIndex: 0, explanation: "The sentence tells a story that is over, so use the Past Simple: kick → kicked. For example: \"She kicked off her shoes.\"" },
        { id: "ps1-8", type: "fillblank", sentence: "I ___ to my best friend on the phone last night.", options: ["talked", "talk", "talks", "talking"], correctIndex: 0, explanation: "A finished action needs -ed: talk → talked. For example: \"They talked for an hour.\"" },
        { id: "ps1-9", type: "fillblank", sentence: "They ___ the tall tree behind the school.", options: ["climbed", "climb", "climbs", "climbing"], correctIndex: 0, explanation: "Regular verbs just add -ed in the Past Simple: climb → climbed. For example: \"We climbed the hill together.\"" },
        { id: "ps1-10", type: "fillblank", sentence: "Mum ___ a big pot of soup last Saturday.", options: ["cooked", "cook", "cooks", "cooking"], correctIndex: 0, explanation: "\"Last Saturday\" is finished, so add -ed: cook → cooked. For example: \"Dad cooked noodles for lunch.\"" },
      ],
    },
    {
      id: "ps-2",
      emoji: "🅴",
      title: "Verbs ending in -e: add -d",
      blurb: "like → liked, dance → danced",
      learn: {
        intro: "If the verb already ends in e, we only need to add d. We never write two e's.",
        headers: ["Now", "Past"],
        rows: [
          ["like", "liked"],
          ["dance", "danced"],
          ["smile", "smiled"],
          ["live", "lived"],
          ["arrive", "arrived"],
          ["close", "closed"],
        ],
        tips: [
          "Just add d: the e is already there.",
          "It works for every verb ending in e: love → loved, save → saved, invite → invited.",
        ],
        mistake: "\"Likeed\" and \"danceed\" are wrong. Write liked and danced.",
      },
      items: [
        { id: "ps2-1", type: "fillblank", sentence: "She ___ the new song at once.", options: ["liked", "likeed", "like", "liking"], correctIndex: 0, explanation: "\"Like\" already ends in e, so add only d: liked. For example: \"He loved the story.\"" },
        { id: "ps2-2", type: "fillblank", sentence: "We ___ all night at the party last Friday.", options: ["danced", "danceed", "dance", "dancing"], correctIndex: 0, explanation: "Dance ends in e, so add only d: danced. For example: \"They danced in the rain.\"" },
        { id: "ps2-3", type: "fillblank", sentence: "The baby ___ when she saw her mum.", options: ["smiled", "smileed", "smile", "smiles"], correctIndex: 0, explanation: "Smile ends in e, so only d is added: smiled. For example: \"Everyone smiled for the photo.\"" },
        { id: "ps2-4", type: "fillblank", sentence: "My uncle ___ in Canada for five years.", options: ["lived", "liveed", "live", "living"], correctIndex: 0, explanation: "The years are finished, so use the Past Simple. Live ends in e, so we add d: lived. For example: \"We lived near the sea.\"" },
        { id: "ps2-5", type: "fillblank", sentence: "The train ___ at the station at noon.", options: ["arrived", "arriveed", "arrive", "arrives"], correctIndex: 0, explanation: "Arrive ends in e, so add only d: arrived. For example: \"The guests arrived early.\"" },
        { id: "ps2-6", type: "fillblank", sentence: "He ___ the window because it was cold.", options: ["closed", "closeed", "close", "closing"], correctIndex: 0, explanation: "Close ends in e, so add only d: closed. For example: \"She closed her book.\"" },
        { id: "ps2-7", type: "fillblank", sentence: "Grandma ___ some cookies for us yesterday.", options: ["baked", "bakeed", "bake", "bakes"], correctIndex: 0, explanation: "Bake ends in e, so we add d: baked. For example: \"Dad baked bread this morning.\"" },
        { id: "ps2-8", type: "fillblank", sentence: "They ___ to a new flat last month.", options: ["moved", "moveed", "move", "moving"], correctIndex: 0, explanation: "\"Last month\" is finished. Move ends in e, so add d: moved. For example: \"Our neighbours moved away in May.\"" },
        { id: "ps2-9", type: "fillblank", sentence: "I ___ all my classmates to my birthday party.", options: ["invited", "inviteed", "invite", "inviting"], correctIndex: 0, explanation: "Invite ends in e, so add only d: invited. For example: \"She invited us to dinner.\"" },
        { id: "ps2-10", type: "fillblank", sentence: "After a long talk, we ___ to stay at home.", options: ["decided", "decideed", "decide", "deciding"], correctIndex: 0, explanation: "Decide ends in e, so add d: decided. For example: \"He decided to try again.\"" },
      ],
    },
    {
      id: "ps-3",
      emoji: "✌️",
      title: "Short verbs: double the last letter",
      blurb: "stop → stopped, plan → planned",
      learn: {
        intro:
          "Some short verbs end in one vowel and one consonant, like s-t-o-p and p-l-a-n. For these, double the last letter and then add -ed.",
        headers: ["Now", "Past"],
        rows: [
          ["stop", "stopped"],
          ["plan", "planned"],
          ["hug", "hugged"],
          ["clap", "clapped"],
          ["chat", "chatted"],
          ["jog", "jogged"],
        ],
        tips: [
          "Do NOT double when there are two vowels before the last letter (wait → waited).",
          "Do NOT double when there are two consonants at the end (help → helped), or when the last letter is w, x or y (fix → fixed, snow → snowed).",
        ],
        mistake: "\"Stoped\" and \"planed\" are wrong. Double the last letter: stopped, planned.",
      },
      items: [
        { id: "ps3-1", type: "fillblank", sentence: "The bus ___ right in front of the school.", options: ["stopped", "stoped", "stopt", "stoping"], correctIndex: 0, explanation: "Stop has one vowel and one consonant at the end, so double the p and add -ed: stopped. For example: \"The car stopped suddenly.\"" },
        { id: "ps3-2", type: "fillblank", sentence: "We ___ a surprise party for our teacher.", options: ["planned", "planed", "plan", "planning"], correctIndex: 0, explanation: "Plan ends in one vowel and one consonant, so double the n: planned. For example: \"They planned a trip to the beach.\"" },
        { id: "ps3-3", type: "fillblank", sentence: "She ___ her little brother tightly.", options: ["hugged", "huged", "hugs", "hugging"], correctIndex: 0, explanation: "Hug is a short verb with one vowel and one consonant, so double the g: hugged. For example: \"He hugged his dog.\"" },
        { id: "ps3-4", type: "fillblank", sentence: "Everyone ___ when the singer finished.", options: ["clapped", "claped", "clap", "claps"], correctIndex: 0, explanation: "Clap has a short vowel and one consonant at the end, so double the p: clapped. For example: \"The crowd clapped and cheered.\"" },
        { id: "ps3-5", type: "fillblank", sentence: "Tom ___ his pencil case on the floor.", options: ["dropped", "droped", "drops", "dropping"], correctIndex: 0, explanation: "Drop ends in one vowel and one consonant, so double the p: dropped. For example: \"She dropped her keys.\"" },
        { id: "ps3-6", type: "fillblank", sentence: "The rabbit ___ across the grass.", options: ["hopped", "hoped", "hops", "hopping"], correctIndex: 0, explanation: "Hop doubles the p: hopped. Careful: \"hoped\" (from hope) is a different word. For example: \"The frog hopped into the pond.\"" },
        { id: "ps3-7", type: "fillblank", sentence: "The girls ___ during the lunch break.", options: ["chatted", "chated", "chat", "chatting"], correctIndex: 0, explanation: "Chat has one vowel and one consonant at the end, so double the t: chatted. For example: \"We chatted for ages.\"" },
        { id: "ps3-8", type: "fillblank", sentence: "Dad ___ around the park before breakfast.", options: ["jogged", "joged", "jog", "jogs"], correctIndex: 0, explanation: "Jog doubles the g: jogged. For example: \"She jogged to the shop.\"" },
        { id: "ps3-9", type: "fillblank", sentence: "We ___ for an hour, but the bus never came.", options: ["waited", "waitted", "wated", "waiting"], correctIndex: 0, explanation: "Wait has TWO vowels before the t (a-i), so we do not double the t: waited. For example: \"He waited by the door.\"" },
        { id: "ps3-10", type: "fillblank", sentence: "The mechanic ___ our car quickly.", options: ["fixed", "fixxed", "fix", "fixing"], correctIndex: 0, explanation: "We never double x, so fix → fixed. For example: \"Dad fixed the bike.\"" },
      ],
    },
    {
      id: "ps-4",
      emoji: "🔤",
      title: "Verbs ending in y",
      blurb: "study → studied, play → played",
      learn: {
        intro:
          "Look at the letter before the y. If it is a consonant (like d in study), change y to i and add -ed. If it is a vowel (like a in play), just add -ed.",
        headers: ["Now", "Past"],
        rows: [
          ["study", "studied"],
          ["carry", "carried"],
          ["try", "tried"],
          ["cry", "cried"],
          ["hurry", "hurried"],
          ["play", "played"],
          ["enjoy", "enjoyed"],
        ],
        tips: [
          "Consonant + y: change y to i, then add -ed (study → studied).",
          "Vowel + y: keep the y and add -ed (play → played, stay → stayed).",
        ],
        mistake: "\"Studyed\" and \"cryed\" are wrong. Change y to i: studied, cried.",
      },
      items: [
        { id: "ps4-1", type: "fillblank", sentence: "She ___ hard for the spelling test.", options: ["studied", "studyed", "studys", "studing"], correctIndex: 0, explanation: "A consonant (d) comes before the y, so change y to i and add -ed: studied. For example: \"He carried the bag home.\"" },
        { id: "ps4-2", type: "fillblank", sentence: "He ___ the heavy bag up the stairs.", options: ["carried", "carryed", "carries", "carrying"], correctIndex: 0, explanation: "Carry ends in consonant + y, so y becomes i: carried. For example: \"She hurried out of the room.\"" },
        { id: "ps4-3", type: "fillblank", sentence: "I ___ to open the jar, but it was stuck.", options: ["tried", "tryed", "tries", "trying"], correctIndex: 0, explanation: "Try ends in consonant + y, so change y to i: tried. For example: \"They tried again.\"" },
        { id: "ps4-4", type: "fillblank", sentence: "The little boy ___ when he lost his toy.", options: ["cried", "cryed", "cries", "crying"], correctIndex: 0, explanation: "Cry ends in consonant + y, so y becomes i: cried. For example: \"The baby cried all night.\"" },
        { id: "ps4-5", type: "fillblank", sentence: "We ___ to catch the last train.", options: ["hurried", "hurryed", "hurries", "hurrying"], correctIndex: 0, explanation: "Hurry ends in consonant + y, so y becomes i: hurried. For example: \"She worried about the exam.\"" },
        { id: "ps4-6", type: "fillblank", sentence: "Kim ___ the words from the board into her notebook.", options: ["copied", "copyed", "copies", "copying"], correctIndex: 0, explanation: "Copy ends in consonant + y, so change y to i: copied. For example: \"He copied the answer carefully.\"" },
        { id: "ps4-7", type: "fillblank", sentence: "The children ___ hide-and-seek all afternoon.", options: ["played", "plaied", "playied", "plays"], correctIndex: 0, explanation: "A VOWEL (a) comes before the y in play, so just add -ed: played. For example: \"We stayed at home.\"" },
        { id: "ps4-8", type: "fillblank", sentence: "We really ___ the film last night.", options: ["enjoyed", "enjoied", "enjoyd", "enjoy"], correctIndex: 0, explanation: "Enjoy has a vowel (o) before the y, so keep the y and add -ed: enjoyed. For example: \"They enjoyed the trip.\"" },
        { id: "ps4-9", type: "fillblank", sentence: "They ___ at a small hotel near the beach.", options: ["stayed", "staied", "stayd", "stay"], correctIndex: 0, explanation: "Stay has a vowel (a) before the y, so just add -ed: stayed. For example: \"She stayed up late.\"" },
        { id: "ps4-10", type: "fillblank", sentence: "Mum ___ when I came home late.", options: ["worried", "worryed", "worrid", "worry"], correctIndex: 0, explanation: "Worry ends in consonant + y, so y becomes i: worried. For example: \"He hurried to school.\"" },
      ],
    },
    {
      id: "ps-5",
      emoji: "🔀",
      title: "Irregular verbs A: vowel changes",
      blurb: "sing → sang, run → ran",
      learn: {
        intro:
          "Irregular verbs do not follow the -ed rule. Their past forms have to be learned, and learning them in groups makes it easier. In this group, the vowel in the middle changes.",
        headers: ["Now", "Past"],
        rows: [
          ["sing", "sang"],
          ["drink", "drank"],
          ["swim", "swam"],
          ["begin", "began"],
          ["run", "ran"],
          ["sit", "sat"],
          ["come", "came"],
          ["give", "gave"],
          ["write", "wrote"],
          ["ride", "rode"],
        ],
        tips: [
          "Be careful with sang / sung, drank / drunk, began / begun. The forms sung, drunk and begun are used with have or has, not for a simple finished action.",
          "The past form is the same for every person: I ran, she ran, they ran.",
        ],
        mistake: "\"Drinked\" and \"runned\" are wrong. Say drank and ran.",
      },
      items: [
        { id: "ps5-1", type: "fillblank", sentence: "The choir ___ beautifully at the concert.", options: ["sang", "sung", "singed", "sing"], correctIndex: 0, explanation: "The past of sing is sang. \"Sung\" is used after have/has. For example: \"She sang her favourite song.\"" },
        { id: "ps5-2", type: "fillblank", sentence: "He ___ a whole bottle of water after the race.", options: ["drank", "drunk", "drinked", "drink"], correctIndex: 0, explanation: "The past of drink is drank. For example: \"We drank hot chocolate after skating.\"" },
        { id: "ps5-3", type: "fillblank", sentence: "We ___ in the sea every morning on holiday.", options: ["swam", "swum", "swimmed", "swim"], correctIndex: 0, explanation: "The past of swim is swam. For example: \"She swam across the pool.\"" },
        { id: "ps5-4", type: "fillblank", sentence: "The lesson ___ at nine o'clock.", options: ["began", "begun", "beginned", "begin"], correctIndex: 0, explanation: "The past of begin is began. For example: \"The film began late.\"" },
        { id: "ps5-5", type: "fillblank", sentence: "She ___ all the way home in the rain.", options: ["ran", "run", "runned", "runs"], correctIndex: 0, explanation: "The past of run is ran. For example: \"The dog ran into the garden.\"" },
        { id: "ps5-6", type: "fillblank", sentence: "The cat ___ on the warm windowsill.", options: ["sat", "sit", "sitted", "sitting"], correctIndex: 0, explanation: "The past of sit is sat. For example: \"He sat next to me.\"" },
        { id: "ps5-7", type: "fillblank", sentence: "My cousins ___ to visit last weekend.", options: ["came", "come", "comed", "comes"], correctIndex: 0, explanation: "The past of come is came. For example: \"Our teacher came in late.\"" },
        { id: "ps5-8", type: "fillblank", sentence: "Mr Lee ___ each student a sticker.", options: ["gave", "give", "gived", "given"], correctIndex: 0, explanation: "The past of give is gave. \"Given\" is used after have/has. For example: \"She gave me a present.\"" },
        { id: "ps5-9", type: "fillblank", sentence: "Ava ___ a letter to her pen friend.", options: ["wrote", "written", "writed", "write"], correctIndex: 0, explanation: "The past of write is wrote. \"Written\" is used after have/has. For example: \"He wrote his name on the board.\"" },
        { id: "ps5-10", type: "fillblank", sentence: "We ___ our bikes along the river.", options: ["rode", "ridden", "rided", "ride"], correctIndex: 0, explanation: "The past of ride is rode. \"Ridden\" is used after have/has. For example: \"They rode home together.\"" },
      ],
    },
    {
      id: "ps-6",
      emoji: "💭",
      title: "Irregular verbs B: -ought and -aught",
      blurb: "buy → bought, catch → caught",
      learn: {
        intro: "These verbs all change to a past form ending in -ought or -aught. Both endings sound like \"awt\".",
        headers: ["Now", "Past"],
        rows: [
          ["buy", "bought"],
          ["bring", "brought"],
          ["think", "thought"],
          ["catch", "caught"],
          ["teach", "taught"],
          ["fight", "fought"],
        ],
        tips: [
          "Learn the two endings together: -ought (bought, brought, thought, fought) and -aught (caught, taught).",
          "The form does not change with the person: I bought, she bought, they bought.",
        ],
        mistake: "\"Buyed\" and \"catched\" are wrong. Say bought and caught.",
      },
      items: [
        { id: "ps6-1", type: "fillblank", sentence: "Mum ___ fresh fish at the market this morning.", options: ["bought", "buyed", "buy", "buys"], correctIndex: 0, explanation: "The past of buy is bought. For example: \"I bought a new notebook.\"" },
        { id: "ps6-2", type: "fillblank", sentence: "Sam ___ his football to school yesterday.", options: ["brought", "bringed", "bring", "brings"], correctIndex: 0, explanation: "The past of bring is brought. For example: \"She brought her lunch.\"" },
        { id: "ps6-3", type: "fillblank", sentence: "I ___ the test was easy, but it was hard.", options: ["thought", "thinked", "think", "thinks"], correctIndex: 0, explanation: "The past of think is thought. For example: \"We thought about it all day.\"" },
        { id: "ps6-4", type: "fillblank", sentence: "The goalkeeper ___ the ball with both hands.", options: ["caught", "catched", "catch", "catches"], correctIndex: 0, explanation: "The past of catch is caught. For example: \"He caught the bus.\"" },
        { id: "ps6-5", type: "fillblank", sentence: "Ms Chan ___ us a new song in the last lesson.", options: ["taught", "teached", "teach", "teaches"], correctIndex: 0, explanation: "The past of teach is taught. For example: \"My dad taught me to swim.\"" },
        { id: "ps6-6", type: "fillblank", sentence: "The team ___ hard until the final whistle.", options: ["fought", "fighted", "fight", "fights"], correctIndex: 0, explanation: "The past of fight is fought. For example: \"They fought for the win.\"" },
        { id: "ps6-7", type: "fillblank", sentence: "We ___ tickets for the show online.", options: ["bought", "buyed", "buy", "buying"], correctIndex: 0, explanation: "The past of buy is bought. For example: \"She bought a red scarf.\"" },
        { id: "ps6-8", type: "fillblank", sentence: "Who ___ this delicious cake to the party?", options: ["brought", "bringed", "brings", "bring"], correctIndex: 0, explanation: "The past of bring is brought. For example: \"Who brought the drinks?\"" },
        { id: "ps6-9", type: "fillblank", sentence: "She ___ about her answer for a long time.", options: ["thought", "thinked", "thinks", "thinking"], correctIndex: 0, explanation: "The past of think is thought. For example: \"He thought hard before speaking.\"" },
        { id: "ps6-10", type: "fillblank", sentence: "He ___ a cold after playing in the rain.", options: ["caught", "catched", "catches", "catching"], correctIndex: 0, explanation: "The past of catch is caught. For example: \"I caught a glimpse of the singer.\"" },
      ],
    },
    {
      id: "ps-7",
      emoji: "🪁",
      title: "Irregular verbs C: -ew",
      blurb: "know → knew, fly → flew",
      learn: {
        intro: "These verbs change to a past form that ends in -ew.",
        headers: ["Now", "Past"],
        rows: [
          ["know", "knew"],
          ["grow", "grew"],
          ["throw", "threw"],
          ["fly", "flew"],
          ["draw", "drew"],
          ["blow", "blew"],
        ],
        tips: [
          "Knew (past of know) sounds the same as new (not old), but they mean different things.",
          "The forms known, grown, thrown, flown, drawn and blown are used after have/has. They are not the simple past.",
        ],
        mistake: "\"Knowed\" and \"throwed\" are wrong. Say knew and threw.",
      },
      items: [
        { id: "ps7-1", type: "fillblank", sentence: "I ___ the answer at once.", options: ["knew", "known", "knowed", "know"], correctIndex: 0, explanation: "The past of know is knew. \"Known\" is used after have/has. For example: \"She knew the way.\"" },
        { id: "ps7-2", type: "fillblank", sentence: "The sunflowers ___ very tall last summer.", options: ["grew", "grown", "growed", "grow"], correctIndex: 0, explanation: "The past of grow is grew. For example: \"The tree grew quickly.\"" },
        { id: "ps7-3", type: "fillblank", sentence: "He ___ the ball to his sister.", options: ["threw", "thrown", "throwed", "throw"], correctIndex: 0, explanation: "The past of throw is threw. For example: \"She threw a paper plane.\"" },
        { id: "ps7-4", type: "fillblank", sentence: "The birds ___ south for the winter.", options: ["flew", "flown", "flied", "fly"], correctIndex: 0, explanation: "The past of fly is flew. For example: \"The kite flew high above the beach.\"" },
        { id: "ps7-5", type: "fillblank", sentence: "Lily ___ a picture of her cat.", options: ["drew", "drawn", "drawed", "draw"], correctIndex: 0, explanation: "The past of draw is drew. For example: \"He drew a big circle.\"" },
        { id: "ps7-6", type: "fillblank", sentence: "The wind ___ the leaves across the yard.", options: ["blew", "blown", "blowed", "blow"], correctIndex: 0, explanation: "The past of blow is blew. For example: \"She blew out the candles.\"" },
        { id: "ps7-7", type: "fillblank", sentence: "Nobody ___ where the keys were.", options: ["knew", "known", "knowed", "knows"], correctIndex: 0, explanation: "The past of know is knew. For example: \"I knew him at school.\"" },
        { id: "ps7-8", type: "fillblank", sentence: "My little brother ___ three centimetres this year.", options: ["grew", "grown", "growed", "grows"], correctIndex: 0, explanation: "The past of grow is grew. For example: \"The plants grew in the sun.\"" },
        { id: "ps7-9", type: "fillblank", sentence: "We ___ to Tokyo last April.", options: ["flew", "flown", "flied", "flies"], correctIndex: 0, explanation: "The past of fly is flew. For example: \"They flew home on Sunday.\"" },
        { id: "ps7-10", type: "fillblank", sentence: "The artist ___ a map of the island.", options: ["drew", "drawn", "drawed", "draws"], correctIndex: 0, explanation: "The past of draw is drew. For example: \"We drew pictures in class.\"" },
      ],
    },
    {
      id: "ps-8",
      emoji: "🟰",
      title: "Irregular verbs D: no change, or -t / -d",
      blurb: "put → put, make → made, send → sent",
      learn: {
        intro:
          "Some irregular verbs do not change at all in the Past Simple, and others swap their ending for -t or -d. Use the time words (yesterday, last week) to tell it is past.",
        headers: ["Now", "Past"],
        rows: [
          ["put", "put"],
          ["cut", "cut"],
          ["let", "let"],
          ["make", "made"],
          ["send", "sent"],
          ["build", "built"],
          ["lose", "lost"],
          ["leave", "left"],
          ["feel", "felt"],
          ["spend", "spent"],
        ],
        tips: [
          "Put, cut and let look the same in the present and the past. Yesterday, she put her bag here.",
          "Others change their ending to -t or -d: send → sent, build → built, make → made, feel → felt.",
        ],
        mistake: "\"Maked\" and \"putted\" are wrong. Say made and put.",
      },
      items: [
        { id: "ps8-1", type: "fillblank", sentence: "She ___ her keys in her bag yesterday.", options: ["put", "putted", "puts", "putting"], correctIndex: 0, explanation: "Put does not change in the Past Simple. \"Yesterday\" tells us it is past. For example: \"He put the book on the shelf last night.\"" },
        { id: "ps8-2", type: "fillblank", sentence: "Dad ___ the cake into eight pieces last night.", options: ["cut", "cutted", "cuts", "cutting"], correctIndex: 0, explanation: "Cut stays the same in the Past Simple. For example: \"She cut her hair last week.\"" },
        { id: "ps8-3", type: "fillblank", sentence: "Our teacher ___ us go home early on Friday.", options: ["let", "letted", "lets", "letting"], correctIndex: 0, explanation: "Let does not change in the past. For example: \"Mum let me stay up late.\"" },
        { id: "ps8-4", type: "fillblank", sentence: "We ___ a poster for the school fair last week.", options: ["made", "maked", "make", "makes"], correctIndex: 0, explanation: "The past of make is made. For example: \"He made a paper boat.\"" },
        { id: "ps8-5", type: "fillblank", sentence: "Grandpa ___ me a postcard from Japan.", options: ["sent", "sended", "send", "sends"], correctIndex: 0, explanation: "The past of send is sent. For example: \"They sent us an invitation.\"" },
        { id: "ps8-6", type: "fillblank", sentence: "The children ___ a sandcastle on the beach.", options: ["built", "builded", "build", "builds"], correctIndex: 0, explanation: "The past of build is built. For example: \"They built a small hut.\"" },
        { id: "ps8-7", type: "fillblank", sentence: "I ___ my umbrella on the bus this morning.", options: ["lost", "losed", "lose", "loses"], correctIndex: 0, explanation: "The past of lose is lost. For example: \"She lost her way in the park.\"" },
        { id: "ps8-8", type: "fillblank", sentence: "The train ___ the station five minutes ago.", options: ["left", "leaved", "leave", "leaves"], correctIndex: 0, explanation: "The past of leave is left. For example: \"We left home at seven.\"" },
        { id: "ps8-9", type: "fillblank", sentence: "She ___ nervous before the speech.", options: ["felt", "feeled", "feel", "feels"], correctIndex: 0, explanation: "The past of feel is felt. For example: \"He felt tired after the run.\"" },
        { id: "ps8-10", type: "fillblank", sentence: "We ___ the whole afternoon at the library.", options: ["spent", "spended", "spend", "spends"], correctIndex: 0, explanation: "The past of spend is spent. For example: \"They spent a week in Osaka.\"" },
      ],
    },
    {
      id: "ps-9",
      emoji: "⭐",
      title: "Irregular verbs E: the must-know verbs",
      blurb: "go → went, be → was / were",
      learn: {
        intro:
          "These are some of the most common verbs in English, and all of them are irregular. It is worth learning them really well.",
        headers: ["Now", "Past"],
        rows: [
          ["go", "went"],
          ["be (I, he, she, it)", "was"],
          ["be (you, we, they)", "were"],
          ["have", "had"],
          ["do", "did"],
          ["see", "saw"],
          ["eat", "ate"],
          ["take", "took"],
          ["get", "got"],
          ["say", "said"],
        ],
        tips: [
          "Be has two past forms: was (I, he, she, it) and were (you, we, they, and plural nouns).",
          "Go → went is completely different from go, so it just has to be remembered.",
        ],
        mistake: "\"Goed\", \"eated\", and \"haved\" are wrong. Say went, ate, and had.",
      },
      items: [
        { id: "ps9-1", type: "fillblank", sentence: "We ___ to the museum on Saturday.", options: ["went", "gone", "goed", "go"], correctIndex: 0, explanation: "The past of go is went. \"Gone\" is used after have/has. For example: \"They went to Paris last year.\"" },
        { id: "ps9-2", type: "fillblank", sentence: "It ___ a sunny day, so we had a picnic.", options: ["was", "were", "is", "be"], correctIndex: 0, explanation: "\"It\" takes was in the past. For example: \"He was late for school.\"" },
        { id: "ps9-3", type: "fillblank", sentence: "The students ___ very quiet during the test.", options: ["were", "was", "are", "be"], correctIndex: 0, explanation: "\"The students\" is plural, so use were. For example: \"We were at the beach.\"" },
        { id: "ps9-4", type: "fillblank", sentence: "I ___ a big breakfast this morning.", options: ["had", "have", "haved", "has"], correctIndex: 0, explanation: "The past of have is had. For example: \"She had a sore throat.\"" },
        { id: "ps9-5", type: "fillblank", sentence: "She ___ her homework before dinner yesterday.", options: ["did", "done", "do", "does"], correctIndex: 0, explanation: "The past of do is did. \"Done\" is used after have/has. For example: \"He did the washing-up.\"" },
        { id: "ps9-6", type: "fillblank", sentence: "Yesterday, I ___ a rainbow after the rain.", options: ["saw", "seen", "seed", "see"], correctIndex: 0, explanation: "The past of see is saw. \"Seen\" is used after have/has. For example: \"We saw a whale on the trip.\"" },
        { id: "ps9-7", type: "fillblank", sentence: "The boys ___ all the sandwiches.", options: ["ate", "eaten", "eated", "eat"], correctIndex: 0, explanation: "The past of eat is ate. For example: \"She ate an apple.\"" },
        { id: "ps9-8", type: "fillblank", sentence: "Dad ___ us to the park last weekend.", options: ["took", "taken", "taked", "take"], correctIndex: 0, explanation: "The past of take is took. \"Taken\" is used after have/has. For example: \"He took a photo of us.\"" },
        { id: "ps9-9", type: "fillblank", sentence: "He ___ a new bike for his birthday.", options: ["got", "get", "gotten", "getted"], correctIndex: 0, explanation: "The past of get is got. For example: \"We got home at six.\"" },
        { id: "ps9-10", type: "fillblank", sentence: "\"Good morning,\" the teacher ___.", options: ["said", "say", "says", "sayed"], correctIndex: 0, explanation: "The past of say is said. For example: He said, 'Come in.'" },
      ],
    },
    {
      id: "ps-10",
      emoji: "❓",
      title: "Did and didn't: questions and negatives",
      blurb: "Did you see it? I didn't go.",
      learn: {
        intro:
          "To make a question or a negative in the Past Simple, we use did or didn't. Did already shows that it is past, so the main verb goes back to its base form.",
        headers: ["Statement", "Question / Negative"],
        rows: [
          ["She went home.", "Did she go home?"],
          ["She went home.", "She didn't go home."],
          ["They ate lunch.", "Did they eat lunch?"],
          ["He saw the film.", "He didn't see the film."],
        ],
        tips: [
          "After did or didn't, use the base verb: go, eat, see. Do NOT use went, ate, or saw again.",
          "Did is used for every person: Did I, did you, did he, did they.",
        ],
        mistake: "\"She didn't went\" and \"Did she went?\" are wrong. Say \"She didn't go\" and \"Did she go?\"",
      },
      items: [
        { id: "ps10-1", type: "fillblank", sentence: "She didn't ___ the answer.", options: ["know", "knew", "known", "knowing"], correctIndex: 0, explanation: "After didn't, use the base verb: know. For example: \"He didn't like the food.\"" },
        { id: "ps10-2", type: "fillblank", sentence: "___ you see the match last night?", options: ["Did", "Do", "Does", "Were"], correctIndex: 0, explanation: "A Past Simple question starts with Did. For example: \"Did she call you?\"" },
        { id: "ps10-3", type: "fillblank", sentence: "He didn't ___ to school yesterday because he was ill.", options: ["go", "went", "gone", "goes"], correctIndex: 0, explanation: "After didn't, the verb goes back to the base form: go. For example: \"We didn't watch TV.\"" },
        { id: "ps10-4", type: "fillblank", sentence: "Did they ___ their homework?", options: ["finish", "finished", "finishing", "finishes"], correctIndex: 0, explanation: "After did, use the base form: finish. For example: \"Did he win the race?\"" },
        { id: "ps10-5", type: "fillblank", sentence: "We ___ eat any breakfast this morning.", options: ["didn't", "don't", "doesn't", "weren't"], correctIndex: 0, explanation: "\"This morning\" is finished, so the negative uses didn't. For example: \"I didn't sleep well last night.\"" },
        { id: "ps10-6", type: "fillblank", sentence: "What time ___ the film start last night?", options: ["did", "does", "do", "was"], correctIndex: 0, explanation: "Past Simple questions use did + base verb: did start. For example: \"Where did you go?\"" },
        { id: "ps10-7", type: "fillblank", sentence: "I didn't ___ my keys anywhere.", options: ["find", "found", "finding", "finds"], correctIndex: 0, explanation: "After didn't, use the base verb: find. For example: \"She didn't hear the bell.\"" },
        { id: "ps10-8", type: "fillblank", sentence: "Did she ___ you the truth?", options: ["tell", "told", "telling", "tells"], correctIndex: 0, explanation: "After did, use the base verb: tell. For example: \"Did he take his umbrella?\"" },
        { id: "ps10-9", type: "fillblank", sentence: "They ___ play outside because it was raining.", options: ["didn't", "don't", "doesn't", "aren't"], correctIndex: 0, explanation: "The reason is in the past (it was raining), so use didn't. For example: \"We didn't go out.\"" },
        { id: "ps10-10", type: "fillblank", sentence: "Where ___ you buy that lovely bag?", options: ["did", "do", "does", "have"], correctIndex: 0, explanation: "Ask about a finished action with did + base verb: did you buy. For example: \"When did they arrive?\"" },
      ],
    },
    {
      id: "ps-11",
      emoji: "✏️",
      title: "Editing: fix the mistake",
      blurb: "Find the error and pick the correct sentence",
      learn: {
        intro:
          "Editing means finding a mistake in a sentence and correcting it. For Past Simple, most mistakes come from a few common problems. Read each sentence slowly and check them one by one.",
        headers: ["Mistake", "Fix"],
        rows: [
          ["goed", "went"],
          ["studyed", "studied"],
          ["stoped", "stopped"],
          ["didn't went", "didn't go"],
          ["they was", "they were"],
        ],
        tips: [
          "Step 1: Look for a time clue (yesterday, last night, ago). That tells you it must be the Past Simple.",
          "Step 2: Check the verb. Is it regular (spelling rule) or irregular (a special form)? After did / didn't, is the verb in the base form?",
        ],
        mistake: "Do not fix only one word and leave another mistake in the sentence. Check the whole sentence.",
      },
      items: [
        { id: "ps11-1", type: "mc", prompt: "Find the mistake and choose the correct sentence: \"Yesterday, we goed to the zoo.\"", options: ["Yesterday, we went to the zoo.", "Yesterday, we go to the zoo.", "Yesterday, we did went to the zoo."], correctIndex: 0, explanation: "Go is irregular: the past is went, not \"goed\". For example: \"Last week, we went to the park.\"" },
        { id: "ps11-2", type: "mc", prompt: "Find the mistake and choose the correct sentence: \"She didn't went to school on Monday.\"", options: ["She didn't go to school on Monday.", "She not went to school on Monday.", "She didn't goes to school on Monday."], correctIndex: 0, explanation: "After didn't, the verb goes back to the base form: go. For example: \"He didn't eat any lunch.\"" },
        { id: "ps11-3", type: "mc", prompt: "Find the mistake and choose the correct sentence: \"He studyed for the test all night.\"", options: ["He studied for the test all night.", "He studyd for the test all night.", "He studies for the test all night."], correctIndex: 0, explanation: "Consonant + y: change y to i and add -ed: studied. For example: \"She tried her best.\"" },
        { id: "ps11-4", type: "mc", prompt: "Find the mistake and choose the correct sentence: \"The kids stoped when the bell rang.\"", options: ["The kids stopped when the bell rang.", "The kids stopt when the bell rang.", "The kids stops when the bell rang."], correctIndex: 0, explanation: "Stop has one vowel and one consonant at the end, so double the p: stopped. For example: \"The car slowed and stopped.\"" },
        { id: "ps11-5", type: "mc", prompt: "Find the mistake and choose the correct sentence: \"Did you saw the rainbow?\"", options: ["Did you see the rainbow?", "Do you saw the rainbow?", "Did you seen the rainbow?"], correctIndex: 0, explanation: "After did, use the base form: see, not saw. For example: \"Did he win the game?\"" },
        { id: "ps11-6", type: "mc", prompt: "Find the mistake and choose the correct sentence: \"I buyed a new pencil case yesterday.\"", options: ["I bought a new pencil case yesterday.", "I buy a new pencil case yesterday.", "I boughted a new pencil case yesterday."], correctIndex: 0, explanation: "Buy is irregular: the past is bought. For example: \"She bought a new hat last week.\"" },
        { id: "ps11-7", type: "mc", prompt: "Find the mistake and choose the correct sentence: \"They was very tired after the trip.\"", options: ["They were very tired after the trip.", "They is very tired after the trip.", "They been very tired after the trip."], correctIndex: 0, explanation: "\"They\" takes were in the past, not was. For example: \"We were late for class.\"" },
        { id: "ps11-8", type: "mc", prompt: "Find the mistake and choose the correct sentence: \"We eated pizza for dinner last night.\"", options: ["We ate pizza for dinner last night.", "We eaten pizza for dinner last night.", "We eat pizza for dinner last night."], correctIndex: 0, explanation: "Eat is irregular: the past is ate. For example: \"They ate breakfast at seven.\"" },
        { id: "ps11-9", type: "mc", prompt: "Find the mistake and choose the correct sentence: \"My mum maked a cake for my birthday.\"", options: ["My mum made a cake for my birthday.", "My mum makes a cake for my birthday.", "My mum making a cake for my birthday."], correctIndex: 0, explanation: "Make is irregular: the past is made. For example: \"Dad made a paper plane.\"" },
        { id: "ps11-10", type: "mc", prompt: "Find the mistake and choose the correct sentence: \"She hurryed to catch the bus.\"", options: ["She hurried to catch the bus.", "She hurryd to catch the bus.", "She hurrys to catch the bus."], correctIndex: 0, explanation: "Consonant + y: change y to i and add -ed: hurried. For example: \"He carried his bag home.\"" },
      ],
    },
  ];
})();
