// Pre-written passages for the Listening module, by tier. Read aloud via
// speechSynthesis — no external API calls. Pitched at an age 10-11 reader.
window.App = window.App || {};
window.App.Content = window.App.Content || {};

(function () {
  window.App.Content.LISTENING_PASSAGES = {
    easy: [
      {
        id: "easy-1",
        text: "Maya packed her backpack the night before the school trip. She was excited to visit the science museum with her class.",
        question: "Where was Maya's class going?",
        options: ["The science museum", "The big city zoo", "The seaside beach"],
        correctIndex: 0,
        explanation: "The passage says Maya was excited to visit the science museum with her class.",
      },
      {
        id: "easy-2",
        text: "During break time, Liam noticed a strange beetle crawling near the fence. He carefully picked it up and showed it to his friends.",
        question: "What did Liam find near the fence?",
        options: ["A beetle", "A frog", "A bird"],
        correctIndex: 0,
        explanation: "Liam noticed a beetle crawling near the fence, then picked it up.",
      },
      {
        id: "easy-3",
        text: "The coach blew her whistle to start practice. The team quickly lined up and began stretching before the game.",
        question: "What did the team do first?",
        options: ["Stretching", "Playing the game", "Going home"],
        correctIndex: 0,
        explanation: "After lining up, the team began stretching — that happened before the game.",
      },
      {
        id: "easy-4",
        text: "Every Sunday, Grandpa takes Ivy to the park to feed the ducks. Today she brought a bag of oats, because Grandpa told her that bread is not good for ducks.",
        question: "What did Ivy bring for the ducks?",
        options: ["A bag of oats", "A loaf of bread", "A box of crackers"],
        correctIndex: 0,
        explanation: "Ivy brought a bag of oats. Grandpa had told her that bread is not good for ducks.",
      },
      {
        id: "easy-5",
        text: "It was raining hard when the bus stopped outside Kai's school. He opened his red umbrella and ran to the gate so that his bag would stay dry.",
        question: "Why did Kai run to the gate?",
        options: ["To keep his bag dry", "To get to class early", "To catch another bus"],
        correctIndex: 0,
        explanation: "He ran so that his bag would stay dry. The bus had already stopped, so he was not trying to catch it.",
      },
      {
        id: "easy-6",
        text: "The bakery on Elm Street opens at seven o'clock. By eight, the shelves are empty, because everyone loves the warm cinnamon rolls.",
        question: "Why are the shelves empty by eight?",
        options: ["Everyone loves the warm rolls", "The baker closes for a rest", "The rolls are too expensive"],
        correctIndex: 0,
        explanation: "The shelves are empty because everyone loves the warm cinnamon rolls, so they sell out quickly.",
      },
      {
        id: "easy-7",
        text: "Mia is learning to swim. Last week she kicked her legs, then she blew bubbles in the water, and today she floated on her back for the first time.",
        question: "What did Mia do today for the first time?",
        options: ["She floated on her back", "She blew some bubbles", "She kicked her legs"],
        correctIndex: 0,
        explanation: "Kicking and blowing bubbles came earlier. Today she floated on her back for the first time.",
      },
      {
        id: "easy-8",
        text: "Tom's little sister cried because her balloon flew away. Tom ran after it, jumped up high, and caught the string just before it reached the tree.",
        question: "What did Tom do to help his sister?",
        options: ["He caught the balloon string", "He bought her a new balloon", "He climbed up the big tree"],
        correctIndex: 0,
        explanation: "Tom jumped up and caught the string before the balloon reached the tree. He did not climb the tree or buy a new balloon.",
      },
      {
        id: "easy-9",
        text: "Ella put on her warm coat, her scarf and her thick gloves before she opened the front door. Then she picked up her sledge and ran outside.",
        question: "What was the weather probably like?",
        options: ["Cold and snowy", "Hot and sunny", "Warm and windy"],
        correctIndex: 0,
        explanation: "Warm clothes and a sledge are clues. They tell us it was cold and snowy, even though the passage never says so.",
      },
      {
        id: "easy-10",
        text: "At the school sports day, Ben was very nervous before the race. His dad told him to just do his best, so Ben smiled and walked to the start line.",
        question: "How did Ben feel after his dad spoke to him?",
        options: ["Calmer and ready to race", "Angrier than he was before", "Too tired to run at all"],
        correctIndex: 0,
        explanation: "Ben smiled and walked to the start line, which shows his dad's words helped him feel calmer and ready.",
      },
    ],
    medium: [
      {
        id: "medium-1",
        text: "The class had been studying volcanoes for two weeks, so when the teacher announced a field trip to the science centre, everyone cheered. They couldn't wait to see the volcano model erupt.",
        question: "Why were the students excited?",
        options: [
          "They were going to see a volcano model erupt",
          "They were getting extra homework for the week",
          "They were going home early that afternoon",
        ],
        correctIndex: 0,
        explanation: "The passage says they couldn't wait to see the volcano model erupt.",
      },
      {
        id: "medium-2",
        text: "Noah spent his Saturday morning building a treehouse with his dad. Halfway through, they realised they didn't have enough nails, so they had to walk to the hardware store.",
        question: "Why did Noah and his dad go to the hardware store?",
        options: ["They ran out of nails", "They wanted snacks", "They needed a ladder"],
        correctIndex: 0,
        explanation: "They realised they didn't have enough nails, which is why they went to the store.",
      },
      {
        id: "medium-3",
        text: "Even though it was her first time performing in front of an audience, Sophie remembered to take a deep breath before she started playing her violin solo.",
        question: "What did Sophie do before her solo?",
        options: ["She took a deep breath", "She left the stage", "She asked for help"],
        correctIndex: 0,
        explanation: "The passage says she took a deep breath before starting her solo.",
      },
      {
        id: "medium-4",
        text: "The library was quiet until a loud crash came from the science corner. Mr Ho rushed over and found a whole shelf of models lying on the floor. Nobody was hurt, but the students spent the afternoon putting the models back.",
        question: "What happened in the science corner?",
        options: ["A shelf of models fell down", "A student dropped a heavy book", "A window was broken by a ball"],
        correctIndex: 0,
        explanation: "Mr Ho found a whole shelf of models on the floor. Nobody was hurt, and no book or window is mentioned.",
      },
      {
        id: "medium-5",
        text: "Farah's plant was drooping, and its leaves were turning yellow. Her teacher asked how often she watered it. \"Every day,\" said Farah. The teacher smiled and explained that too much water can harm a plant just as badly as too little.",
        question: "Why was Farah's plant unhealthy?",
        options: ["It was getting too much water", "It was standing in too much shade", "It was planted in the wrong pot"],
        correctIndex: 0,
        explanation: "Farah watered it every day, and the teacher explained that too much water can harm a plant. Shade and the pot are never mentioned.",
      },
      {
        id: "medium-6",
        text: "The tour guide checked her list twice, counted the children again, and looked back at the empty bench by the fountain. \"We are one short,\" she said quietly, and she began to walk faster.",
        question: "What can we infer about the guide?",
        options: ["She is worried a child is missing", "She is bored by the long tour", "She is angry about her lost list"],
        correctIndex: 0,
        explanation: "Counting again, looking back and walking faster are signs of worry. She says \"one short\", so a child seems to be missing.",
      },
      {
        id: "medium-7",
        text: "Before the bake sale, Nadia mixed the batter, poured it into a tin and slid it into the oven. While it baked, she made the icing. She spread the icing only after the cake had cooled down completely.",
        question: "What did Nadia do right after the cake came out of the oven?",
        options: ["She waited for it to cool", "She spread the icing on top", "She mixed the batter again"],
        correctIndex: 0,
        explanation: "The icing went on only after the cake had cooled, so she had to wait for it to cool first.",
      },
      {
        id: "medium-8",
        text: "The town's old cinema was going to be pulled down. Residents wrote letters, a girl named Rui collected signatures at the market, and the local newspaper printed the story. In the end, the council agreed to keep the building.",
        question: "What is the passage mainly about?",
        options: ["People working together to save a building", "A newspaper printing stories about a market", "A girl who wanted to go to the cinema"],
        correctIndex: 0,
        explanation: "Residents, Rui and the newspaper all worked to save the cinema, and it worked. That is the main idea; the market and the newspaper are only details.",
      },
      {
        id: "medium-9",
        text: "On a hot afternoon, the ferry to Cheung Chau was delayed because thick fog had settled over the harbour. Passengers waited on the pier, fanning themselves and sipping cold drinks, until the captain announced that the fog was lifting.",
        question: "Why was the ferry delayed?",
        options: ["A thick fog covered the harbour", "The engine broke down at the pier", "Too many passengers were waiting"],
        correctIndex: 0,
        explanation: "The delay was caused by thick fog over the harbour. The passengers were only waiting because of it.",
      },
      {
        id: "medium-10",
        text: "Hugo said, \"It's fine,\" but he stared at the floor and pushed his food around his plate without eating. He didn't even laugh at his sister's joke. His mum knew that his team had lost the match that morning.",
        question: "What is Hugo probably feeling?",
        options: ["Disappointed, although he says he is fine", "Excited, because his next match is tomorrow", "Tired, because he woke up too early today"],
        correctIndex: 0,
        explanation: "His words say he is fine, but his actions show he is not. His mum knew the team had lost, so he is disappointed.",
      },
    ],
    hard: [
      {
        id: "hard-1",
        text: "The expedition team had trekked for six hours through dense rainforest before they finally spotted the waterfall they had been searching for. Exhausted but thrilled, they set up camp nearby to rest before the climb ahead.",
        question: "How did the team likely feel when they found the waterfall?",
        options: ["Exhausted but thrilled", "Bored and disappointed", "Angry and confused"],
        correctIndex: 0,
        explanation: "The passage directly describes them as \"exhausted but thrilled\" after finding it.",
      },
      {
        id: "hard-2",
        text: "Although the science fair project didn't win first place, Priya's research on renewable energy impressed the judges enough that she was invited to present at the regional competition.",
        question: "What can you infer about Priya's project?",
        options: [
          "It was strong even without winning first place",
          "It was the weakest project at the whole fair",
          "It was mainly about volcanoes and earthquakes",
        ],
        correctIndex: 0,
        explanation: "Being invited to the regional competition shows the judges were impressed, even without first place.",
      },
      {
        id: "hard-3",
        text: "The old lighthouse keeper had warned the sailors about the coming storm, but by the time they turned the ship around, the waves were already crashing over the deck.",
        question: "What happened after the lighthouse keeper's warning?",
        options: [
          "The sailors turned back too late and the storm hit",
          "The sailors ignored the keeper's warning completely",
          "The storm never came and the sea stayed calm",
        ],
        correctIndex: 0,
        explanation: "By the time they turned around, waves were already crashing — so they reacted too late.",
      },
      {
        id: "hard-4",
        text: "When the volunteers arrived at the beach, the sand looked clean from a distance. Up close, though, it was full of tiny plastic pieces no bigger than a grain of rice. Leila realised that picking up bottles and bags would not be enough, because the smallest fragments would have to be sieved out by hand.",
        question: "What did Leila realise?",
        options: ["Picking up bottles alone would not be enough", "The beach was already clean enough to leave", "The volunteers should go home before dark"],
        correctIndex: 0,
        explanation: "Leila saw that bottles and bags were only part of the problem, because the tiny fragments also had to be removed.",
      },
      {
        id: "hard-5",
        text: "The coach did not shout when Sam missed the final shot. She simply handed him a bottle of water, sat down beside him and said, \"Tell me what you saw just before you let go of the ball.\" Sam thought for a moment, and then he began to explain.",
        question: "What does the coach's response suggest about her attitude?",
        options: ["She wants him to learn from the mistake", "She is too tired to be angry with him", "She does not care about the final result"],
        correctIndex: 0,
        explanation: "By asking Sam to describe what he saw, the coach helps him think about the miss and learn from it. She stays calm and shows interest.",
      },
      {
        id: "hard-6",
        text: "Although the museum guide called the ancient vase priceless, she added that its value came less from the gold painted on it than from what it revealed about how the potters had lived four thousand years ago. \"A pot can be a diary,\" she said.",
        question: "According to the guide, why is the vase so valuable?",
        options: ["It shows how the potters lived long ago", "It is covered in a thick layer of gold", "It is the largest vase ever discovered"],
        correctIndex: 0,
        explanation: "Its value comes less from the gold and more from what it tells us about the potters' lives. That is why she calls it a diary.",
      },
      {
        id: "hard-7",
        text: "Rain is forecast for Saturday, so the school has moved sports day to Friday. Students who cannot come on Friday must bring a note from a parent by Wednesday, otherwise they will be marked absent. Everyone else should wear their house colours.",
        question: "What must a student do if they cannot attend on Friday?",
        options: ["Bring a note from a parent by Wednesday", "Come in on Saturday for the sports day", "Tell the teacher on Friday before class"],
        correctIndex: 0,
        explanation: "Students who cannot come must bring a parent's note by Wednesday. The sports day has moved, so Saturday is not used.",
      },
      {
        id: "hard-8",
        text: "The two brothers argued about who should carry the tent. Finally, their father pointed out that it would be easier to share the load, so they hung it from a pole and carried it between them. By the time they reached the campsite, neither of them was complaining.",
        question: "What can we infer from the last sentence?",
        options: ["Sharing the load ended the argument", "The tent had become much lighter", "Their father carried it in the end"],
        correctIndex: 0,
        explanation: "Once they shared the load, neither brother complained. The tent was as heavy as before, and the father did not carry it.",
      },
      {
        id: "hard-9",
        text: "Scientists tracking a group of sea turtles noticed that the turtles always turned left at the same point, although there was nothing visible in the water. They eventually discovered a strong ocean current there, which the turtles used to save energy on their long journey.",
        question: "Why did the turtles turn left?",
        options: ["To use a current that saved energy", "To avoid a large rock in the water", "To follow a boat that was passing"],
        correctIndex: 0,
        explanation: "The turtles turned to use a strong ocean current, which saved energy. The passage says there was nothing visible in the water.",
      },
      {
        id: "hard-10",
        text: "Historians used to think the ancient town was abandoned suddenly. But when archaeologists examined the houses, they found that the tools and pots were missing and that the doorways had been carefully blocked with stones. This suggests that the people left slowly, and expected to return.",
        question: "What do the missing tools and blocked doorways suggest?",
        options: ["The people left in an organised way", "The city was attacked without warning", "The houses were never finished at all"],
        correctIndex: 0,
        explanation: "People who take their tools and carefully block their doors have planned to leave. A surprise attack would not leave the town like that.",
      },
    ],
    expert: [
      {
        id: "expert-1",
        text: "Despite years of research, scientists still debate why some species migrate thousands of miles each year while closely related species remain in the same region permanently. One theory suggests it comes down to subtle genetic differences passed down over many generations.",
        question: "According to the passage, what might explain why some species migrate and others don't?",
        options: [
          "Subtle genetic differences passed down over generations",
          "All species migrate in exactly the same way each year",
          "Migration has been fully explained by scientists",
        ],
        correctIndex: 0,
        explanation: "The passage states one theory points to subtle genetic differences passed down over generations.",
      },
      {
        id: "expert-2",
        text: "The city council's decision to convert the abandoned railway into a public park was met with mixed reactions; while many residents welcomed the green space, local historians argued that the tracks should have been preserved as a monument to the town's industrial past.",
        question: "Why did some historians disagree with the council's decision?",
        options: [
          "They wanted the railway kept as a historical monument",
          "They did not want any new parks built anywhere in town",
          "They thought the new park would be far too expensive",
        ],
        correctIndex: 0,
        explanation: "The historians argued the tracks should have been preserved as a monument, not turned into a park.",
      },
      {
        id: "expert-3",
        text: "By the time the negotiations concluded, both sides had made concessions neither had originally intended to make, a reminder that compromise often requires giving up more than either party expects going in.",
        question: "What does the passage suggest about compromise?",
        options: [
          "It often requires giving up more than expected",
          "It never requires anyone to make any sacrifice",
          "Only one side ever needs to give something up",
        ],
        correctIndex: 0,
        explanation: "The passage says compromise \"often requires giving up more than either party expects.\"",
      },
      {
        id: "expert-4",
        text: "Economists describe a sunk cost as money that has already been spent and cannot be recovered. The surprising finding is that people often carry on with a failing project precisely because they have already invested so much in it, even when stopping would save them more money in the long run.",
        question: "What is surprising about sunk costs?",
        options: ["People carry on because of past spending", "People never spend money on failing projects", "Sunk costs can easily be recovered later"],
        correctIndex: 0,
        explanation: "The surprise is that people continue because of what they have already spent, even when stopping would save money. The passage says sunk costs cannot be recovered.",
      },
      {
        id: "expert-5",
        text: "The author of the report did not claim that the new bridge caused the drop in traffic accidents. Instead, she pointed out that accidents had already begun to fall before the bridge opened, and that the same decline had been seen in towns that had no new bridges at all.",
        question: "What is the author's main point?",
        options: ["The bridge may not be why accidents fell", "The bridge made no difference to any town", "Accidents rose in towns without new bridges"],
        correctIndex: 0,
        explanation: "Accidents were already falling before the bridge and in towns without one, so the bridge may not be the cause. She does not say it made no difference.",
      },
      {
        id: "expert-6",
        text: "The mayor described the new tax as a modest contribution, yet his speech mentioned neither the amount nor the date on which it would be collected. Reporters noticed that the pauses before his answers grew longer as their questions became more specific.",
        question: "What does the passage imply about the mayor?",
        options: ["He was avoiding giving clear details", "He was confident about every answer", "He had not understood the questions"],
        correctIndex: 0,
        explanation: "He left out the amount and the date, and his pauses grew longer when the questions got specific. This suggests he was avoiding clear details.",
      },
      {
        id: "expert-7",
        text: "During the nineteenth century, many factories were built beside rivers, because the water turned their wheels and carried away their waste. Only later did towns realise that the same rivers supplied their drinking water, and that the convenience of the factory owners had come at a cost to everyone downstream.",
        question: "What does \"at a cost to everyone downstream\" suggest?",
        options: ["The pollution harmed people further along the river", "Factory owners paid heavily for all the water they used", "Towns downstream built the factories themselves"],
        correctIndex: 0,
        explanation: "The waste went into the river and reached the people who drank from it further along. The passage says the owners gained convenience, not that they paid for it.",
      },
      {
        id: "expert-8",
        text: "Although the reviewer praises the film's beautiful photography, she says that the story feels like a series of postcards: each scene is lovely to look at, yet none of them seems to lead to the next. She concludes that watching it is like admiring a photograph album rather than following a journey.",
        question: "What is the reviewer's opinion of the film?",
        options: ["It looks lovely but lacks a connected story", "It has a clever plot but poor pictures", "It is unpleasant to watch from start to end"],
        correctIndex: 0,
        explanation: "She praises the photography, but says the scenes do not lead to one another, like postcards. So it looks lovely but has no connected story.",
      },
      {
        id: "expert-9",
        text: "The ancient sailors of the Pacific had no maps of the open sea. Instead, they memorised the positions of stars, the direction of ocean swells and the flight paths of birds. Their knowledge was passed down in songs, which, unlike written notes, could be remembered and performed during the voyage itself.",
        question: "Why were songs a useful way to keep this knowledge?",
        options: ["They could be remembered and used during voyages", "They were written on charts that ships carried", "They were sung to keep sailors awake at night"],
        correctIndex: 0,
        explanation: "Unlike written notes, songs could be remembered and performed during the voyage itself. The sailors had no maps or charts.",
      },
      {
        id: "expert-10",
        text: "Whenever the committee received a complaint, it issued a statement promising to look carefully into the matter. Years later, a researcher checked the records and found that, out of forty complaints, not one had led to any change at all.",
        question: "What does the finding suggest about the committee's statements?",
        options: ["They promised action but never delivered it", "They were always followed by careful reforms", "They were written by the people who complained"],
        correctIndex: 0,
        explanation: "The statements promised careful attention, but none of the forty complaints led to any change. So the promises were not followed by action.",
      },
    ],
  };
})();
