// Module 4: Reading — two passages per tier, each followed by a mix of
// multiple-choice and fill-in-the-blank questions with explanations.
window.App = window.App || {};
window.App.Content = window.App.Content || {};

(function () {
  window.App.Content.READING_ITEMS = {
    easy: [
      {
        id: "read-easy-1",
        passage:
          "Lily loves to visit her grandmother's farm every summer. The old farmhouse sits at the top of a hill, surrounded by fields that turn gold in July. Every morning, before the sun gets too hot, Lily and her grandmother put on their boots and head out to the henhouse together. She helps feed the chickens, gathers warm eggs still nestled in the straw, and picks ripe tomatoes and crunchy cucumbers from the garden out back. Her favourite job, though, is brushing the old grey pony that lives in the barn. In the evenings, when the chores are finally done, Lily and her grandmother sit together on the porch swing, sipping lemonade and watching the sky turn orange and pink as the sun sets over the fields.",
        questions: [
          { type: "mc", prompt: "Which of these does Lily NOT do on the farm, according to the passage?", options: ["Milk the cows in the big barn", "Collect eggs from the henhouse", "Pick tomatoes from the garden"], correctIndex: 0, explanation: "Lily gathers eggs and picks vegetables, but the passage never says she milks cows. Only a pony is mentioned in the barn." },
          { type: "mc", prompt: "Why do Lily and her grandmother head out to the henhouse \"before the sun gets too hot\"?", options: ["Because the cooler morning is a comfortable time to work outside", "Because the chickens only lay their eggs very early at sunrise", "Because Lily has to catch the school bus early every morning"], correctIndex: 0, explanation: "The passage does not say the chickens lay only at sunrise, and it is summer holiday time. Working before the heat makes the chores pleasant, which is the sensible reason." },
          { type: "fillblank", sentence: "In the evenings, Lily and her grandmother sit on the ___ swing, sipping lemonade.", options: ["porch", "garden", "barn"], correctIndex: 0, explanation: "The garden and the barn are both places in the story, but the passage says they sit together on the porch swing." },
        ],
      },
      {
        id: "read-easy-2",
        passage:
          "When the school picnic was cancelled because of sudden rain, Mr. Kim's class groaned with disappointment. But instead of just handing out worksheets, Mr. Kim rolled a cart of board games into the classroom and announced an indoor tournament instead. Teams rotated between chess, checkers, and a giant floor puzzle, earning points for their table each time they won a round. By the end of the afternoon, the classroom was filled with laughter instead of complaints, and several students said the rainy day had turned into one of their favourite days of the whole year.",
        questions: [
          { type: "mc", prompt: "What does Mr. Kim's reaction tell us about him?", options: ["He tried to turn a disappointing day into a fun one", "He was annoyed that the picnic was cancelled", "He wanted the class to work quietly on worksheets"], correctIndex: 0, explanation: "The passage says he did NOT just hand out worksheets. He brought board games and started a tournament instead, so he made the best of the rain." },
          { type: "fillblank", sentence: "Teams earned ___ for their table each time they won a round.", options: ["points", "stickers", "prizes"], correctIndex: 0, explanation: "The passage says teams were \"earning points for their table\". Stickers and prizes are not mentioned." },
          { type: "mc", prompt: "Which of these was NOT one of the games in the tournament?", options: ["A spelling quiz", "Checkers", "A giant floor puzzle"], correctIndex: 0, explanation: "The teams rotated between chess, checkers, and a giant floor puzzle. A spelling quiz is not mentioned." },
        ],
      },
      {
        id: "read-easy-3",
        passage:
          "Jay stood at the edge of the pool and held his towel tightly. His friends were already splashing in the water, but his legs felt like jelly. \"I can't do it,\" he whispered. His teacher, Miss Wong, smiled and handed him a bright blue kickboard. \"You don't have to swim today,\" she said. \"Just hold this and kick your feet.\" Jay took a deep breath and slid into the water. At first, he kicked very slowly. Then his legs began to move faster, and he glided across the pool. When he reached the other side, he was grinning from ear to ear.",
        questions: [
          { type: "mc", prompt: "Why did Jay whisper \"I can't do it\"?", options: ["He was nervous about going into the water", "He was tired after playing with his friends", "He had left his swimming goggles at home"], correctIndex: 0, explanation: "His legs \"felt like jelly\" and he held his towel tightly. These are signs of nerves. His friends were splashing, but Jay had not even got in yet." },
          { type: "fillblank", sentence: "Miss Wong gave Jay a bright blue ___ to hold.", options: ["kickboard", "towel", "float"], correctIndex: 0, explanation: "Jay had his own towel, but Miss Wong handed him a bright blue kickboard." },
          { type: "mc", prompt: "What happened right after Jay took a deep breath?", options: ["He slid into the water and kicked slowly", "He glided across the pool on his back", "Miss Wong took the kickboard away from him"], correctIndex: 0, explanation: "He slid in and kicked slowly at first. Gliding across the pool came later, and the kickboard was never taken away." },
        ],
      },
      {
        id: "read-easy-4",
        passage:
          "Every morning, a small bee visits the flowers in Grandpa's garden. It lands on a yellow flower and drinks a sweet liquid called nectar. While it drinks, yellow dust called pollen sticks to its furry legs. When the bee flies to the next flower, some of the pollen rubs off. This helps the plant make seeds, which grow into new flowers. The bee carries the rest of the nectar back to its hive, where it is turned into honey. Without bees, Grandpa's garden would have far fewer flowers.",
        questions: [
          { type: "mc", prompt: "How do bees help the plants in the garden?", options: ["Pollen rubs off as they move between flowers, helping plants make seeds", "They eat the nectar so that the flowers grow much bigger and stronger", "They turn the nectar they drink into new seeds inside the warm hive"], correctIndex: 0, explanation: "The bee carries pollen between flowers, which helps plants make seeds. Nectar becomes honey in the hive, not seeds." },
          { type: "fillblank", sentence: "The bee drinks a sweet liquid called ___ .", options: ["nectar", "pollen", "honey"], correctIndex: 0, explanation: "All three words are in the passage. Pollen is the yellow dust, and honey is made later in the hive. The sweet liquid is nectar." },
          { type: "mc", prompt: "Which sentence is NOT true, according to the passage?", options: ["Bees make their honey from pollen", "Pollen sticks to the bee's legs", "The bee brings nectar to its hive"], correctIndex: 0, explanation: "Honey is made from nectar, not pollen. The other two statements appear in the passage." },
        ],
      },
      {
        id: "read-easy-5",
        passage:
          "On Saturday morning, Nina helped her dad make bread. First, they mixed flour, water, yeast and a little salt in a big bowl. Then Nina pressed the dough with her hands until it felt soft and smooth. \"Now we have to wait,\" said Dad, covering the bowl with a cloth. Nina wanted to bake it at once, but Dad explained that the yeast needed time to work. After an hour, the dough had doubled in size. They baked it in the oven for thirty minutes, and the whole flat filled with a warm smell. Nina couldn't wait to taste it.",
        questions: [
          { type: "mc", prompt: "Why did Dad tell Nina to wait?", options: ["The yeast needed time to make the dough rise", "The oven still needed time to heat up properly", "The dough was too sticky to press any more"], correctIndex: 0, explanation: "Dad explained that the yeast needed time to work, and the dough had doubled in size after an hour. Nothing is said about the oven, and the dough was already soft." },
          { type: "fillblank", sentence: "After an hour, the dough had ___ in size.", options: ["doubled", "shrunk", "tripled"], correctIndex: 0, explanation: "The passage says the dough had doubled in size. It grew, so it did not shrink, and it did not triple." },
          { type: "mc", prompt: "Which order is correct?", options: ["Mix the ingredients, press the dough, wait, bake", "Mix the ingredients, bake, wait, press the dough", "Wait, mix the ingredients, press the dough, bake"], correctIndex: 0, explanation: "They mixed, then Nina pressed the dough, then they waited an hour, and finally they baked it." },
        ],
      },
      {
        id: "read-easy-6",
        passage:
          "Maya wanted to make a rainbow at home. Her teacher had said that sunlight looks white, but it is really made of many colours mixed together. Maya filled a clear glass with water and put it on the window ledge, so the sunlight shone through it. Under the glass, she placed a sheet of white paper. As the light passed through the water, it bent and split into colours. Soon, a small rainbow of red, yellow, green and blue appeared on the paper. Maya smiled. She had made a rainbow without any rain!",
        questions: [
          { type: "mc", prompt: "What did Maya learn about sunlight?", options: ["It looks white but is really made of many colours", "It only looks white when it shines through glass", "It is coloured by the water it passes through"], correctIndex: 0, explanation: "Her teacher said sunlight looks white but is made of many colours. The water only bends and splits the light. It does not colour it." },
          { type: "fillblank", sentence: "Maya put a sheet of white ___ under the glass.", options: ["paper", "cloth", "plastic"], correctIndex: 0, explanation: "The passage says she placed a sheet of white paper under the glass, and the rainbow appeared on it." },
          { type: "mc", prompt: "Why did the rainbow appear on the paper?", options: ["The water bent the light and split it into colours", "The white paper had rainbow colours painted on its surface", "The window ledge reflected the sunlight onto the wall"], correctIndex: 0, explanation: "The passage says the light bent and split into colours as it passed through the water. The paper was white and was just where the colours landed." },
        ],
      },
    ],
    medium: [
      {
        id: "read-medium-1",
        passage:
          "The class hamster, Nibbles, went missing over the weekend, and by Monday morning the classroom was in a state of quiet panic. Ms. Reyes had left food and water in his cage on Friday, certain the little door was latched shut, but somehow Nibbles had squeezed through a gap no one had noticed before. The students spent the entire morning searching every corner of the room — behind the bookshelves, under the reading rug, even inside backpacks left open overnight. Just when it seemed like Nibbles might be gone for good, Marcus knelt down by the reading corner and heard a faint rustling sound coming from an old rubber boot someone had left by the window. Sure enough, curled up inside, fast asleep, was Nibbles, looking as comfortable as if the boot had been built just for him. Everyone cheered, and Ms. Reyes reminded the class, gently but firmly, to always double-check the cage door from now on.",
        questions: [
          { type: "mc", prompt: "What does the passage suggest about how Nibbles escaped?", options: ["He squeezed through an unnoticed gap although the door looked latched", "A student left the cage door open when leaving on Friday afternoon", "Ms. Reyes forgot to give him any food and water, so he went looking"], correctIndex: 0, explanation: "Nibbles was already missing over the weekend, and Ms. Reyes had left food and water and was certain the door was latched. The escape came through an unnoticed gap." },
          { type: "fillblank", sentence: "Marcus found Nibbles because he heard a faint ___ sound coming from an old boot.", options: ["rustling", "squeaking", "scratching"], correctIndex: 0, explanation: "All three words sound possible, but the passage says he heard a faint rustling sound." },
          { type: "mc", prompt: "Which place did the students NOT search for Nibbles?", options: ["Out in the school garden", "Under the big reading rug", "Inside some of the backpacks"], correctIndex: 0, explanation: "The students searched behind the bookshelves, under the rug, and inside backpacks. The school garden is never mentioned." },
        ],
      },
      {
        id: "read-medium-2",
        passage:
          "When the empty lot next to Rosa's block of flats sat unused for years, filled with weeds and broken glass, a group of neighbours decided to turn it into a community garden instead. Rosa, then eleven years old, helped her mother clear trash on the very first weekend of the project, not expecting much to come of it. Over the next few months, though, raised planting beds appeared, then rows of tomatoes and peppers, and eventually a small bench where neighbours who barely knew each other before started stopping to chat. By the following summer, the garden was producing enough vegetables that families took turns bringing bags of fresh produce to a local food pantry, and Rosa, now in charge of watering the tomato beds, felt proud every time she walked past the lot that used to be empty.",
        questions: [
          { type: "mc", prompt: "Which sequence matches how the garden developed?", options: ["Cleared trash, built raised beds, grew vegetables, shared produce with a food pantry","Built raised beds, cleared the trash, added a bench, grew vegetables, shared produce", "Shared produce with a food pantry, planted tomatoes, cleared the trash, built beds"], correctIndex: 0, explanation: "Rosa helped clear trash on the first weekend. Raised beds and vegetables came over the next months, and the food pantry donations came by the following summer." },
          { type: "fillblank", sentence: "The small ___ became a place where neighbours who barely knew each other stopped to chat.", options: ["bench", "planting bed", "fence"], correctIndex: 0, explanation: "Planting beds appear in the story too, but the passage says neighbours stopped to chat at a small bench." },
          { type: "mc", prompt: "What does Rosa's feeling at the end of the passage suggest?", options: ["She felt proud because she watched the project grow from nothing", "She felt relieved that the long project was finally finished", "She felt disappointed that the garden had stayed so small"], correctIndex: 0, explanation: "She felt proud every time she walked past the lot that \"used to be empty\". Nothing in the passage suggests relief or disappointment." },
        ],
      },
      {
        id: "read-medium-3",
        passage:
          "Every autumn, Ken's grandmother made paper lanterns for the Mid-Autumn Festival, and this year Ken asked to help. She showed him how to bend thin bamboo strips into a frame, then cover it with red paper. Ken's first lantern turned out lopsided, and the paper tore when he pulled it too tightly. He wanted to give up. \"Every lantern I ever made started badly,\" his grandmother said calmly. \"The trick is to go slowly and try again.\" On his third attempt, Ken worked patiently, pressing the paper down gently instead of pulling it. When the frame was finished, they put a small battery light inside. That evening, Ken's lantern glowed in the window, its uneven shape casting warm, wobbly shadows across the wall. To Ken, it was better than any lantern he could have bought.",
        questions: [
          { type: "mc", prompt: "What does Ken's grandmother mean by \"Every lantern I ever made started badly\"?", options: ["Even experts make mistakes at first, so he should not give up", "Her lanterns were always bad, so he should not expect much", "He should stop now and buy a finished lantern instead"], correctIndex: 0, explanation: "She says it calmly, and then tells him to go slowly and try again. She is encouraging him. She is not criticising her own work." },
          { type: "mc", prompt: "Why did Ken's first lantern tear?", options: ["He pulled the paper too tightly", "The bamboo frame was too thin", "The paper was the wrong colour"], correctIndex: 0, explanation: "The passage says the paper tore when he pulled it too tightly. The frame and the colour are not blamed." },
          { type: "fillblank", sentence: "On his third attempt, Ken pressed the paper down ___ instead of pulling it.", options: ["gently", "firmly", "quickly"], correctIndex: 0, explanation: "He \"worked patiently, pressing the paper down gently\". Pressing firmly or quickly would risk tearing it again." },
        ],
      },
      {
        id: "read-medium-4",
        passage:
          "Bats are not blind, but they hunt in the dark, when even good eyesight would not help much. Instead, they use a clever skill called echolocation. As a bat flies, it makes high-pitched sounds that people cannot hear. These sounds travel through the air until they hit an object, such as a moth, and bounce back as echoes. The bat's large ears catch the echoes, and its brain works out how far away the object is, how big it is, and even which way it is moving. Some bats can catch hundreds of insects in a single hour this way. Scientists have studied echolocation to help design better sonar for ships and aids for blind people.",
        questions: [
          { type: "mc", prompt: "Why is echolocation more useful to bats than eyesight when they hunt at night?", options: ["It still works in the dark, when eyesight would not help much", "It lets bats see colours more clearly than other animals can", "Bats cannot see at all, so they have no other way to hunt"], correctIndex: 0, explanation: "The passage says bats are NOT blind, but eyesight would not help much in the dark. Echolocation works without light." },
          { type: "mc", prompt: "Which order describes how echolocation works?", options: ["The bat makes a sound, the sound bounces off an object, the bat's ears catch the echo", "An object makes a sound, the bat's ears catch it, and then the bat makes an echo back", "The bat's ears make a sound, the sound hits the ground, the bat's brain catches it"], correctIndex: 0, explanation: "The bat makes the sound, it bounces back from an object as an echo, and the bat's ears catch the echo." },
          { type: "fillblank", sentence: "Scientists have studied echolocation to help design better ___ for ships.", options: ["sonar", "radar", "engines"], correctIndex: 0, explanation: "Sonar uses sound, just as a bat does. Radar uses radio waves, so it is not the answer the passage gives." },
        ],
      },
      {
        id: "read-medium-5",
        passage:
          "On her way home from school, Mei noticed a tourist standing on the pavement, turning a map round and round with a puzzled look. \"Excuse me,\" the man said slowly. \"Star Ferry? Where?\" Mei's English was not perfect, but she wanted to help. She pointed down the road and said, \"Straight, then left.\" The man still looked confused, so Mei took out her phone and showed him the route on a map. Then she walked with him to the corner and pointed at the sea in the distance. \"There! Star Ferry!\" she said. The man laughed with relief and thanked her three times. On the walk home, Mei felt proud. She realised that clear gestures and a few simple words could be enough to help someone.",
        questions: [
          { type: "mc", prompt: "What did Mei learn from this experience?", options: ["Simple words and clear gestures can be enough to help someone", "She needs to improve her English before she helps anyone else", "Tourists usually prefer paper maps to using their phones"], correctIndex: 0, explanation: "The last sentence says exactly this. Her English \"was not perfect\", but she still helped." },
          { type: "mc", prompt: "Why did the man still look confused after Mei said \"Straight, then left\"?", options: ["Her short directions were not enough for him to follow", "He had changed his mind about going to the Star Ferry", "He thought Mei had pointed in the wrong direction"], correctIndex: 0, explanation: "Mei then showed him the map and walked him to the corner. That suggests the words alone were not enough. He was clearly trying to find the ferry." },
          { type: "fillblank", sentence: "Mei took out her ___ and showed him the route on a map.", options: ["phone", "notebook", "camera"], correctIndex: 0, explanation: "The passage says she took out her phone. The man had a paper map, and this was a different one." },
        ],
      },
      {
        id: "read-medium-6",
        passage:
          "Tam was the last runner in the school relay team, and everyone expected her to bring them a medal. But at the final changeover, the baton slipped from her teammate Ryo's hand and bounced across the track. By the time Ryo picked it up, two other teams had passed him. Tam felt her heart sink, but when she took the baton, she ran as fast as she could. She caught up with one team on the final bend and crossed the line in third place. Ryo apologised over and over, but Tam only shrugged. \"We didn't get gold,\" she said, \"but we didn't give up.\" Later, their coach told the team that the way they had recovered mattered more than the mistake.",
        questions: [
          { type: "mc", prompt: "What can we infer about Tam from the way she reacted?", options: ["She valued effort and teamwork more than winning", "She was secretly angry with Ryo for dropping it", "She did not really care how the race turned out"], correctIndex: 0, explanation: "She only shrugged and said they didn't give up. That shows she cared, and she was kind to Ryo. She was not angry with him." },
          { type: "mc", prompt: "Which statement about the race is true?", options: ["The team finished third after Ryo dropped the baton", "The team finished first, but only by a tiny margin", "Tam dropped the baton at the last changeover point"], correctIndex: 0, explanation: "It was Ryo's hand the baton slipped from, not Tam's. The team crossed the line in third place." },
          { type: "fillblank", sentence: "The coach said that the way the team had ___ mattered more than the mistake.", options: ["recovered", "started", "finished"], correctIndex: 0, explanation: "The coach's point was about how the team recovered after the baton was dropped. It was not about how they started or finished." },
        ],
      },
    ],
    hard: [
      {
        id: "read-hard-1",
        passage:
          "Deforestation in tropical regions has accelerated sharply over the past decade, driven largely by the expansion of agricultural land for crops and cattle grazing. Conservationists warn that the consequences reach far beyond the forests themselves. Rainforests play a critical role in regulating rainfall patterns across entire continents, meaning their loss can disrupt farming and water supplies for millions of people who may live thousands of miles away from the original site of clearing. The forests also serve as one of the planet's largest natural stores of carbon, so cutting and burning them releases greenhouse gases that were locked away for centuries. In response, a growing number of governments have begun experimenting with financial incentive programs, paying farmers directly to preserve standing forest rather than clear it for new fields. Early results from several of these programs have been promising, though researchers caution that incentives alone are unlikely to solve a problem driven by such enormous economic pressure to keep expanding farmland.",
        questions: [
          { type: "mc", prompt: "Why do the researchers caution that payments to farmers are unlikely to solve deforestation on their own?", options: ["The pressure to expand farmland is enormous, so payments may not be enough", "Farmers refuse to accept money from governments because they distrust them", "The early results showed that the programs had failed completely"], correctIndex: 0, explanation: "The passage calls early results \"promising\", so the programs did not fail. The caution is that incentives face \"enormous economic pressure\" to keep expanding farmland." },
          { type: "mc", prompt: "Which statement about deforestation is best supported by the passage?", options: ["Clearing a forest in one place can affect farming and water supplies far away", "Deforestation only harms the animals and plants that live in the cleared forest", "Burning forests releases gases that were created by the trees that same year"], correctIndex: 0, explanation: "Rainforests regulate rainfall across continents, so the effects reach people thousands of miles away. The greenhouse gases were \"locked away for centuries\", not created that year." },
          { type: "fillblank", sentence: "The forests serve as one of the planet's largest natural ___ of carbon.", options: ["stores", "sources", "producers"], correctIndex: 0, explanation: "Forests hold carbon, and burning them releases it. That makes them a store of carbon, not a source of it." },
        ],
      },
      {
        id: "read-hard-2",
        passage:
          "Streaming services and online stores increasingly rely on recommendation algorithms to suggest what a user might want to watch or buy next, based largely on patterns drawn from that user's own past behaviour and the behaviour of similar users. While these systems can feel remarkably accurate at times, researchers have raised concerns about a phenomenon known as the \"filter bubble,\" in which users are repeatedly shown content similar to what they've already engaged with, gradually narrowing the range of ideas, products, or perspectives they encounter. Some technology companies have begun experimenting with deliberately injecting more variety into recommendations, arguing that a slightly less \"accurate\" but more diverse set of suggestions may actually serve users better in the long run. Critics of this approach counter that most users simply want convenience, and that occasionally showing irrelevant content risks frustrating them without meaningfully broadening their perspectives in practice.",
        questions: [
          { type: "mc", prompt: "Why might a company accept recommendations that are \"slightly less accurate\"?", options: ["It believes a wider variety may serve users better in the long run", "Its algorithm no longer has enough data about what the user likes", "It wants its users to spend a lot less time on the service each day"], correctIndex: 0, explanation: "The passage says these companies argue that a more diverse set of suggestions may serve users better in the long run." },
          { type: "mc", prompt: "What do the two sides in the passage mainly disagree about?", options: ["Whether users are better served by variety or by convenience", "Whether recommendation algorithms are accurate enough for users", "Whether companies should be allowed to collect data about users"], correctIndex: 0, explanation: "Both sides accept that algorithms can be accurate. The company side argues for variety, while critics argue that users mostly want convenience." },
          { type: "fillblank", sentence: "A \"filter bubble\" gradually ___ the range of ideas and perspectives a user encounters.", options: ["narrows", "widens", "hides"], correctIndex: 0, explanation: "Seeing similar content again and again gradually narrows what you encounter. A bubble makes the range smaller, not larger." },
        ],
      },
      {
        id: "read-hard-3",
        passage:
          "Coral reefs cover less than one per cent of the ocean floor, yet they are home to about a quarter of all marine species. Reefs are built by tiny animals called coral polyps, which produce hard skeletons of limestone. Over thousands of years, these skeletons pile up to form vast structures. Polyps also live in partnership with microscopic algae, which grow inside their tissues. The algae use sunlight to make food, and they share much of it with the coral, while the coral gives the algae shelter. This partnership explains why reefs are found in shallow, clear water, where sunlight can reach them. However, when the water becomes too warm, the coral can expel its algae. Without them, the coral loses its colour and much of its food supply, a condition known as bleaching. Bleached coral is not dead, but it is weak, and if the water does not cool soon enough, it may die.",
        questions: [
          { type: "mc", prompt: "Why are coral reefs usually found in shallow, clear water?", options: ["The algae inside the coral need sunlight to make food", "Coral polyps cannot survive under the pressure of deep water", "Limestone only forms near the surface"], correctIndex: 0, explanation: "The passage links the partnership with algae directly to the water being shallow and clear, \"where sunlight can reach them\". The other two reasons are never stated." },
          { type: "mc", prompt: "According to the passage, what does bleaching mean for coral?", options: ["The coral has lost its algae and is weak, but it may recover if the water cools", "The coral has died completely and turned bright white, so it cannot recover", "The coral has grown too large for the reef and is being pushed out by other coral"], correctIndex: 0, explanation: "Bleached coral \"is not dead, but it is weak\". If the water cools soon enough, it can survive." },
          { type: "mc", prompt: "How does the passage describe the relationship between coral and algae?", options: ["Each gives the other something it needs", "The algae feed on the coral until it dies", "The coral uses the algae only as decoration"], correctIndex: 0, explanation: "The algae make food from sunlight and share it, and the coral gives the algae shelter. It is a partnership that helps both." },
        ],
      },
      {
        id: "read-hard-4",
        passage:
          "Before the fifteenth century, books in Europe were copied by hand, usually by monks, and a single Bible could take months to finish. Because of this, books were very expensive, and only the wealthy and religious institutions owned them. That began to change around 1440, when a German goldsmith named Johannes Gutenberg developed a printing press using movable metal type. Individual letters could be arranged into a page, printed many times, and then rearranged to make a different page. Books could now be produced far faster and more cheaply than before. Within a few decades, printing presses had spread across Europe, and millions of books were in circulation. As reading material became more affordable, more people learned to read, and ideas spread faster than ever before. Historians often argue that this shift helped fuel major developments such as the Renaissance and the Scientific Revolution, although they also point out that these changes had many causes, not just one invention.",
        questions: [
          { type: "mc", prompt: "Why were books so expensive before the printing press?", options: ["Each copy had to be written out by hand, which took a very long time", "Paper was extremely rare and had to be brought in from other countries", "Monks refused to sell their books to anyone except very rich noblemen"], correctIndex: 0, explanation: "A single Bible could take months to copy by hand. That labour explains the price. Paper shortages and refusals to sell are not mentioned." },
          { type: "mc", prompt: "What made movable type so useful?", options: ["Letters could be rearranged into new pages, so books were made faster and cheaper", "It gave monks a much faster way of writing out each separate copy of a book by hand", "It made the paper used for making books much cheaper and far easier to produce"], correctIndex: 0, explanation: "The passage says letters could be arranged, printed many times, and then rearranged for a new page. That is why printing was faster and cheaper." },
          { type: "mc", prompt: "How does the passage treat the idea that printing caused the Renaissance and the Scientific Revolution?", options: ["As one important factor among several causes", "As the one and only cause of both of them", "As a claim that no serious historian believes"], correctIndex: 0, explanation: "Historians say printing helped \"fuel\" these developments, but they also point out that there were many causes, not just one invention." },
        ],
      },
      {
        id: "read-hard-5",
        passage:
          "Scientists still do not fully understand why we sleep, yet they agree that it is essential. During sleep, the brain does not simply switch off. Instead, it replays and organises the day's memories, moving important information into long-term storage. Sleep is also when the body does much of its repair work, and children's bodies release growth hormone mainly during deep sleep. People who regularly sleep too little find it harder to concentrate, learn, and control their emotions, and studies link long-term sleep loss to health problems. Children aged six to twelve generally need nine to twelve hours of sleep each night, and teenagers need eight to ten. Unfortunately, many young people fall short, partly because bright screens in the evening can delay the body's natural signal that it is time to sleep. Experts therefore suggest putting devices away about an hour before bed.",
        questions: [
          { type: "mc", prompt: "Why might a student who sleeps badly struggle in class?", options: ["Sleep helps the brain store what it learns, and too little hurts concentration", "Sleep is when the body grows taller, so they feel too small for their desk", "Students who sleep badly usually have weaker eyesight and hearing in class"], correctIndex: 0, explanation: "The passage links sleep to memory storage and says lack of sleep makes it harder to concentrate and learn. Growth and eyesight have nothing to do with it here." },
          { type: "mc", prompt: "What does the passage say about screens in the evening?", options: ["They can delay the body's signal that it is time to sleep", "They make the deep stages of sleep last longer at night", "They are harmless as long as the room is kept dark"], correctIndex: 0, explanation: "Bright screens can delay the body's natural signal. That is why experts suggest putting devices away about an hour before bed." },
          { type: "mc", prompt: "Which statement is NOT supported by the passage?", options: ["Scientists have proved exactly why humans need sleep", "The brain organises its memories while we are asleep", "Teenagers usually need about eight to ten hours of sleep"], correctIndex: 0, explanation: "The first sentence says scientists \"still do not fully understand why we sleep\". The other two statements appear in the passage." },
        ],
      },
      {
        id: "read-hard-6",
        passage:
          "Electric cars are becoming more common, and many governments hope they will help cut air pollution. Unlike petrol cars, electric cars produce no exhaust fumes when driving, which makes city air cleaner. They can also be cheaper to run, since electricity often costs less than fuel, and they have fewer moving parts to repair. However, they are not a perfect solution. Batteries are expensive and take a long time to charge compared with filling a tank, and in many places there are still too few charging points. In addition, an electric car is only as clean as the electricity that powers it: if that electricity comes from burning coal, the pollution has simply moved from the car to the power station. Manufacturing the battery also uses large amounts of energy and raw materials. For these reasons, many experts say electric cars are a step in the right direction, but not the whole answer.",
        questions: [
          { type: "mc", prompt: "Why does the passage say an electric car is \"only as clean as the electricity that powers it\"?", options: ["If the power comes from coal, the pollution is just produced elsewhere", "Electric cars produce a lot of exhaust fumes when the battery is low", "Charging a car every night always damages its battery in the long run"], correctIndex: 0, explanation: "The passage explains that with coal power, the pollution moves from the car to the power station. It never mentions exhaust fumes from electric cars or battery damage." },
          { type: "mc", prompt: "Which advantage of electric cars does the passage mention?", options: ["They can be cheaper to run and have fewer parts to repair", "They charge much faster than a petrol tank can be filled", "Their batteries are cheap to make and use few raw materials"], correctIndex: 0, explanation: "The passage says electricity often costs less than fuel and there are fewer moving parts. It says batteries are expensive and slow to charge, so the other two options are the opposite." },
          { type: "mc", prompt: "What is the writer's overall view of electric cars?", options: ["They are helpful, but not a complete solution", "They will soon replace all petrol cars", "They are worse for the environment than petrol cars"], correctIndex: 0, explanation: "The last sentence sums it up: a step in the right direction, but not the whole answer." },
        ],
      },
    ],
    expert: [
      {
        id: "read-expert-1",
        passage:
          "The concept of \"planned obsolescence\" refers to the practice of designing products with an artificially limited lifespan, encouraging consumers to repurchase items more frequently than strictly necessary. The term dates back to the early twentieth century, when some manufacturers began deliberately engineering products to fail or become outdated after a set period, rather than building them to last indefinitely. Critics argue this practice generates unnecessary waste, drives up consumer costs over time, and contributes significantly to environmental harm, particularly as electronic devices are discarded at growing rates. Manufacturers, for their part, counter that shorter product cycles allow for continuous innovation, arguing that consumers benefit from regular improvements in performance, safety, and design that would be slower to arrive if products were built to last for decades. The debate has intensified in recent years as electronic waste has become one of the fastest-growing categories of waste worldwide, prompting several governments to consider \"right to repair\" legislation that would require manufacturers to make products easier and cheaper to fix rather than replace.",
        questions: [
          { type: "mc", prompt: "Based on the passage, what is the main aim of \"right to repair\" laws?", options: ["To make products easier and cheaper to fix instead of replace", "To stop manufacturers from releasing any new models each year", "To force companies to build products that last for decades"], correctIndex: 0, explanation: "The laws would require products to be easier and cheaper to fix. The passage never says new models would be banned or that products must last decades." },
          { type: "mc", prompt: "Which statement would a manufacturer, as described in the passage, most likely agree with?", options: ["Regular product upgrades bring improvements in performance and safety", "Products should be designed to last as long as they possibly can", "Electronic waste is not really a serious problem for anyone in the world"], correctIndex: 0, explanation: "Manufacturers say shorter product cycles bring regular improvements. Building products to last as long as possible is the critics' position." },
          { type: "mc", prompt: "Which of these is NOT a criticism of planned obsolescence mentioned in the passage?", options: ["It slows down technological innovation", "It creates a lot of unnecessary waste", "It raises costs for consumers over time"], correctIndex: 0, explanation: "Innovation is the manufacturers' argument in favour of shorter product cycles, not a criticism. Critics mention waste, rising costs, and environmental harm." },
        ],
      },
      {
        id: "read-expert-2",
        passage:
          "In an economy where digital content is often free to access, some economists argue that the actual product being sold isn't the content itself but rather the user's attention, which is then packaged and sold to advertisers. This framing, often called the \"attention economy,\" helps explain design choices that might otherwise seem puzzling: autoplay features, infinite scrolling feeds, and notification systems engineered to maximise the frequency with which users return to a platform. Critics of the attention economy argue that these design choices exploit well-documented psychological vulnerabilities, particularly among younger users whose capacity for self-regulation is still developing, and that the incentives driving platform design are fundamentally misaligned with users' long-term wellbeing. Defenders of the model counter that users retain the ability to disengage at any time, and that blaming design features shifts responsibility away from personal choice. The debate remains largely unresolved, complicated further by the fact that the companies best positioned to study these effects rigorously are often the same companies whose business models depend on the behaviours being studied.",
        questions: [
          { type: "mc", prompt: "Why does the passage say features like autoplay and infinite scrolling \"might otherwise seem puzzling\"?", options: ["Without that idea, it is unclear why free content is built to keep people watching", "They are very expensive for the platforms to build and to maintain over many years", "Most users say that they dislike being kept on the platform for so long each day"], correctIndex: 0, explanation: "If content is free, it is puzzling why platforms work so hard to keep you there. The attention-economy idea explains it: your attention is what is being sold." },
          { type: "mc", prompt: "Which statement would a defender of the attention-economy model, as described in the passage, most likely make?", options: ["People can choose to stop using a platform, so responsibility lies with them", "Young users cannot easily stop, so these platforms should be banned for them", "Platforms should be redesigned to reduce the time people spend on them"], correctIndex: 0, explanation: "Defenders say users can disengage at any time and that blaming design shifts responsibility away from personal choice. The other two are closer to the critics' concerns." },
          { type: "mc", prompt: "Why is research on these effects made harder by who is best placed to do it?", options: ["The best-placed researchers profit from the behaviours they study, so may be biased", "Independent researchers are banned from studying social media platforms directly", "The companies refuse to release any of their data to outside researchers at all"], correctIndex: 0, explanation: "The passage only says that the companies best placed to study the effects depend on the very behaviours being studied. It does not claim researchers are banned or data is never shared." },
        ],
      },
      {
        id: "read-expert-3",
        passage:
          "For decades, many people assumed that growing up with two languages confused children and slowed their learning. More recent research has challenged that view. Studies suggest that bilingual people constantly manage two languages in their minds, choosing one and holding the other back, and some researchers argue that this daily practice strengthens a mental skill known as executive control, which helps people switch attention and ignore distractions. Early experiments appeared to show that bilingual children outperformed single-language peers on such tasks. However, later studies, using larger and more carefully matched groups, have often failed to reproduce the effect, and some scientists now doubt that the cognitive advantage is as large, or as general, as first claimed. What is less disputed are the practical and cultural benefits: bilingual people can communicate with more people, access more information, and often show greater sensitivity to how others see the world. The debate shows how a striking early result can be much harder to confirm than to announce.",
        questions: [
          { type: "mc", prompt: "Why does the writer mention that later studies used \"larger and more carefully matched groups\"?", options: ["To show the later studies were better designed, so their findings matter more", "To argue that small studies are always wrong and should be ignored completely", "To show that the children were sorted into groups by the language they spoke"], correctIndex: 0, explanation: "Larger, matched groups make results more reliable. That is why the failure to reproduce the effect matters. The passage does not say small studies are always wrong." },
          { type: "mc", prompt: "Which statement best sums up the research described?", options: ["The mental advantage is disputed, but the practical and cultural benefits are less so", "Bilingualism has been clearly proved to slow down children's learning in the classroom", "Bilingualism has been clearly proved to make children far more intelligent overall"], correctIndex: 0, explanation: "The old view of confusion has been challenged, and the mental advantage is now doubted by some scientists. The practical benefits are \"less disputed\". Nothing has been \"proved\" in either direction." },
          { type: "mc", prompt: "What is the final sentence mainly suggesting?", options: ["Exciting early findings can be much harder to confirm than to announce", "Scientists should stop announcing any early results to the public", "Research about bilingualism is no longer worth doing at all by anyone"], correctIndex: 0, explanation: "The last sentence says a striking early result can be harder to confirm than to announce. It is a comment on how science works, not advice to stop research." },
        ],
      },
      {
        id: "read-expert-4",
        passage:
          "In many medical trials, some patients are given a pill that contains no active ingredient, called a placebo, and yet a surprising number report feeling better. This is known as the placebo effect. It does not mean that the patients were imagining their symptoms. Brain scans suggest that expectation can trigger real changes, such as the release of the body's natural painkillers, and the effect appears strongest for conditions involving pain, nausea and low mood. Its strength also depends on how the placebo is given: larger pills, injections and confident doctors seem to produce stronger results than small pills and hesitant ones. Placebos do not shrink tumours or cure infections. Researchers therefore use them mainly as a comparison, so they can tell whether a new treatment truly works beyond what patients' expectations alone would achieve. This raises an ethical puzzle: doctors are expected to be honest with patients, yet a placebo may work best when the patient believes it is real medicine.",
        questions: [
          { type: "mc", prompt: "Why do researchers use placebos in medical trials?", options: ["To measure how much a new treatment achieves beyond patients' expectations", "To cure patients whose symptoms are only mild, or that would soon go away", "To make sure patients never find out that they are taking part in any trial"], correctIndex: 0, explanation: "The passage says placebos are used \"mainly as a comparison\", so researchers can tell whether a treatment works beyond expectation alone. Curing patients is not their purpose." },
          { type: "mc", prompt: "What does the passage say about patients who feel better after taking a placebo?", options: ["Their improvement can be real, as expectation can change the body", "They were probably exaggerating or simply imagining their symptoms", "They must have had a mild illness that would have healed anyway"], correctIndex: 0, explanation: "The passage says this \"does not mean that the patients were imagining their symptoms\", and brain scans show real changes such as painkillers being released." },
          { type: "mc", prompt: "What is the \"ethical puzzle\" in the last sentence?", options: ["Honesty with patients may make a placebo less effective", "Placebos are too expensive to give to every patient", "Doctors do not know which patients need placebos"], correctIndex: 0, explanation: "Doctors are expected to be honest, but a placebo may work best when the patient believes it is real medicine. Those two things pull in opposite directions." },
        ],
      },
      {
        id: "read-expert-5",
        passage:
          "On a hot summer night, the centre of a large city can be several degrees warmer than the countryside around it. This is called the urban heat island effect. Dark surfaces such as asphalt and roofs absorb sunlight during the day and release it slowly after sunset, while concrete and glass trap heat between tall buildings that also block cooling breezes. Cities also have fewer plants and trees, which normally cool the air by releasing water vapour. Air conditioners add to the problem by pumping hot air outdoors, so the hotter it gets, the more they are used. Planners have proposed several remedies: planting trees, painting roofs white or pale to reflect sunlight, and building green roofs. These measures can reduce temperatures by a few degrees, but they are not free, and space in crowded cities is scarce. In addition, the benefits are not always shared equally, since wealthier neighbourhoods often have more trees and parks than poorer ones.",
        questions: [
          { type: "mc", prompt: "Why does the passage describe air conditioning as part of the problem?", options: ["It pumps hot air outdoors, so more heat means more use", "It uses up large amounts of the water that trees would need", "It makes buildings darker so they absorb even more heat"], correctIndex: 0, explanation: "The passage says air conditioners pump hot air outdoors, and higher heat means more use. That creates a cycle. Water and darker buildings are not mentioned." },
          { type: "mc", prompt: "Why do trees help cool a city?", options: ["They release water vapour, which cools the air around them", "They absorb sunlight by day and release it slowly at night", "They reflect sunlight away in the same way as pale roofs"], correctIndex: 0, explanation: "The absorbing and slow releasing of heat is what asphalt and dark roofs do. Trees cool the air by releasing water vapour." },
          { type: "mc", prompt: "What point does the final sentence make?", options: ["Solutions for heat may benefit some neighbourhoods more than others", "Poorer neighbourhoods do not want more trees planted near their homes", "Wealthier areas are cooler because they use less air conditioning"], correctIndex: 0, explanation: "Wealthier areas often already have more trees and parks. So cooling measures may not help all neighbourhoods equally. The passage does not give the other two reasons." },
        ],
      },
      {
        id: "read-expert-6",
        passage:
          "Wikipedia is written and edited by volunteers, and anyone can change most of its pages. To many people, this sounds like a recipe for chaos, yet the encyclopedia is widely used, and some studies of its science articles have found accuracy comparable to traditional encyclopaedias. Several features help explain this. Every change is recorded, so mistakes and vandalism can be reversed quickly, often within minutes. Editors are expected to back up claims with published sources, and statements without a source can be challenged or deleted. Disagreements are settled on public discussion pages, where editors must explain their reasoning. Nevertheless, the system has weaknesses. Articles on popular topics receive many careful edits, while obscure subjects may have few readers to notice errors. Volunteer editors are also not a perfect cross-section of society, which can affect which topics receive attention. For these reasons, teachers often advise treating Wikipedia as a starting point for research rather than a final authority.",
        questions: [
          { type: "mc", prompt: "Why does the writer mention that changes can be reversed \"within minutes\"?", options: ["To show that mistakes and vandalism are often corrected quickly", "To argue that nobody can safely trust any page on the whole site", "To show that professional editors are paid to check every change"], correctIndex: 0, explanation: "Because every change is recorded, errors can be undone quickly. The passage says the editors are volunteers, so nobody is paid." },
          { type: "mc", prompt: "Which weakness of Wikipedia does the passage mention?", options: ["Errors on obscure topics may go unnoticed as few people read them", "Popular topics receive very few edits from truly careful editors", "Every change is deleted automatically after about a week or so"], correctIndex: 0, explanation: "The passage says popular articles receive many careful edits, while obscure subjects may have few readers to notice errors. The other two options are not stated." },
          { type: "mc", prompt: "What does the final sentence advise?", options: ["Use it to begin research, then check other sources", "Never use it for schoolwork or any serious research", "Trust it completely because volunteers check it"], correctIndex: 0, explanation: "Teachers suggest treating it as a starting point rather than a final authority, so the next step is to check other sources." },
        ],
      },
    ],
  };
})();
