// Vocabulary Builder — 20 items per tier (mostly single words, a few common
// phrases tagged pos:"phrase"), each with English word, part of speech,
// Traditional Chinese translation, a simple definition, and an example
// sentence. Some items also carry `synonyms`/`antonyms` ({word, zh} pairs)
// for the tap-to-explore related-words feature.
window.App = window.App || {};
window.App.Content = window.App.Content || {};

(function () {
  window.App.Content.VOCABULARY_ITEMS = {
    easy: [
      { word: "gigantic", pos: "adj", zh: "巨大的", definition: "extremely large", example: "The gigantic whale swam past our boat." },
      { word: "delighted", pos: "adj", zh: "非常高興的", definition: "very pleased", example: "She was delighted with her birthday gift." },
      { word: "curious", pos: "adj", zh: "好奇的", definition: "eager to know or learn something", example: "The curious cat explored every room." },
      { word: "ancient", pos: "adj", zh: "古老的", definition: "very old, from long ago", example: "We visited some ancient ruins in Rome.", antonyms: [{ word: "modern", zh: "現代的" }] },
      { word: "brave", pos: "adj", zh: "勇敢的", definition: "showing courage", example: "The brave firefighter rescued the kitten.", antonyms: [{ word: "afraid", zh: "害怕的" }] },
      { word: "wander", pos: "verb", zh: "漫遊；閒逛", definition: "to walk around without a clear direction", example: "We wandered through the old town." },
      { word: "vanish", pos: "verb", zh: "消失", definition: "to disappear suddenly", example: "The magician made the coin vanish.", antonyms: [{ word: "appear", zh: "出現" }] },
      { word: "journey", pos: "noun", zh: "旅程", definition: "a trip from one place to another", example: "Their journey across the country took five days." },
      { word: "treasure", pos: "noun", zh: "寶藏", definition: "a collection of valuable things", example: "The pirates buried their treasure on the island." },
      { word: "narrow", pos: "adj", zh: "狹窄的", definition: "having a small width", example: "The narrow path led up the mountain.", synonyms: [{ word: "thin", zh: "薄的" }], antonyms: [{ word: "wide", zh: "寬闊的" }] },
      { word: "polite", pos: "adj", zh: "有禮貌的", definition: "having good manners", example: "It's polite to say thank you.", antonyms: [{ word: "rude", zh: "無禮的" }] },
      { word: "arrive", pos: "verb", zh: "到達", definition: "to reach a place", example: "We arrived at the station on time.", synonyms: [{ word: "reach", zh: "到達" }], antonyms: [{ word: "depart", zh: "離開" }] },
      { word: "borrow", pos: "verb", zh: "借（入）", definition: "to take something and return it later", example: "Can I borrow your pencil?", antonyms: [{ word: "lend", zh: "借出" }] },
      { word: "silent", pos: "adj", zh: "安靜的；沉默的", definition: "making no sound", example: "The library was completely silent.", synonyms: [{ word: "quiet", zh: "安靜的" }], antonyms: [{ word: "noisy", zh: "吵鬧的" }] },
      { word: "message", pos: "noun", zh: "訊息", definition: "a short piece of information sent to someone", example: "She left a message on his phone." },
      { word: "protect", pos: "verb", zh: "保護", definition: "to keep someone or something safe", example: "A helmet protects your head.", synonyms: [{ word: "defend", zh: "保衛" }] },
      { word: "give up", pos: "phrase", zh: "放棄", definition: "to stop trying", example: "Don't give up on your dreams." },
      { word: "look forward to", pos: "phrase", zh: "期待", definition: "to feel excited about something that will happen", example: "I look forward to the holidays." },
      { word: "in the end", pos: "phrase", zh: "最終；到頭來", definition: "eventually, after everything", example: "In the end, they decided to stay home." },
      { word: "enormous", pos: "adj", zh: "巨大的", definition: "very big in size", example: "They live in an enormous house." },
    ],
    medium: [
      { word: "reluctant", pos: "adj", zh: "不情願的", definition: "unwilling to do something", example: "He was reluctant to try the spicy food.", antonyms: [{ word: "eager", zh: "渴望的" }] },
      { word: "persuade", pos: "verb", zh: "說服", definition: "to convince someone to do something", example: "She persuaded her parents to get a dog." },
      { word: "exhausted", pos: "adj", zh: "精疲力盡的", definition: "extremely tired", example: "After the race, the runners were exhausted.", synonyms: [{ word: "tired", zh: "疲倦的" }] },
      { word: "generous", pos: "adj", zh: "慷慨的", definition: "willing to give freely", example: "He was generous and shared his lunch.", antonyms: [{ word: "selfish", zh: "自私的" }] },
      { word: "hesitate", pos: "verb", zh: "猶豫", definition: "to pause because you are unsure", example: "Don't hesitate to ask for help." },
      { word: "astonish", pos: "verb", zh: "使震驚；使驚訝", definition: "to surprise someone greatly", example: "The magic trick astonished the audience.", synonyms: [{ word: "amaze", zh: "使驚奇" }] },
      { word: "resourceful", pos: "adj", zh: "足智多謀的", definition: "good at finding quick, clever solutions", example: "The resourceful team fixed the robot with tape." },
      { word: "anxious", pos: "adj", zh: "焦慮的", definition: "worried or nervous", example: "She felt anxious before the exam.", antonyms: [{ word: "calm", zh: "冷靜的" }] },
      { word: "achievement", pos: "noun", zh: "成就", definition: "something accomplished successfully", example: "Winning the competition was a huge achievement." },
      { word: "determination", pos: "noun", zh: "決心", definition: "firmness of purpose", example: "Her determination helped her finish the marathon." },
      { word: "confident", pos: "adj", zh: "自信的", definition: "feeling sure about your abilities", example: "She felt confident before the exam.", antonyms: [{ word: "nervous", zh: "緊張的" }] },
      { word: "collapse", pos: "verb", zh: "倒塌；崩潰", definition: "to fall down suddenly", example: "The old bridge collapsed during the storm." },
      { word: "isolate", pos: "verb", zh: "隔離；孤立", definition: "to separate something from others", example: "The scientists isolated the virus for study." },
      { word: "abundant", pos: "adj", zh: "豐富的", definition: "existing in large quantities", example: "Fresh water is abundant in this region.", antonyms: [{ word: "scarce", zh: "稀少的" }] },
      { word: "clumsy", pos: "adj", zh: "笨拙的", definition: "moving in an awkward way, likely to drop things", example: "He's a bit clumsy in the kitchen.", antonyms: [{ word: "graceful", zh: "優雅的" }] },
      { word: "sincere", pos: "adj", zh: "真誠的", definition: "honest and genuine", example: "He gave a sincere apology.", synonyms: [{ word: "genuine", zh: "真誠的" }], antonyms: [{ word: "fake", zh: "虛假的" }] },
      { word: "assist", pos: "verb", zh: "協助", definition: "to help someone", example: "The nurse assisted the doctor during surgery.", synonyms: [{ word: "help", zh: "幫助" }] },
      { word: "make up your mind", pos: "phrase", zh: "下定決心", definition: "to decide something", example: "It's time to make up your mind." },
      { word: "keep an eye on", pos: "phrase", zh: "留意；照看", definition: "to watch something carefully", example: "Can you keep an eye on my bag?" },
      { word: "run out of", pos: "phrase", zh: "用完", definition: "to have no more of something", example: "We ran out of milk this morning." },
    ],
    hard: [
      { word: "inevitable", pos: "adj", zh: "不可避免的", definition: "certain to happen", example: "Change was inevitable as the city grew." },
      { word: "skeptical", pos: "adj", zh: "懷疑的", definition: "having doubts about something", example: "He was skeptical about the new plan.", antonyms: [{ word: "convinced", zh: "確信的" }] },
      { word: "articulate", pos: "adj / verb", zh: "表達清晰的；清楚表達", definition: "able to express ideas clearly", example: "She gave an articulate speech." },
      { word: "persevere", pos: "verb", zh: "堅持不懈", definition: "to continue despite difficulty", example: "He persevered through months of training." },
      { word: "ambiguous", pos: "adj", zh: "模稜兩可的", definition: "unclear or open to more than one meaning", example: "The instructions were ambiguous.", antonyms: [{ word: "clear", zh: "清晰的" }] },
      { word: "underestimate", pos: "verb", zh: "低估", definition: "to think something is smaller or less important than it is", example: "Never underestimate a determined opponent.", antonyms: [{ word: "overestimate", zh: "高估" }] },
      { word: "controversy", pos: "noun", zh: "爭議", definition: "a disagreement about something", example: "The new rule caused a lot of controversy." },
      { word: "legitimate", pos: "adj", zh: "合法的；正當的", definition: "reasonable or acceptable", example: "She had a legitimate reason for being late." },
      { word: "compromise", pos: "noun / verb", zh: "妥協", definition: "an agreement where each side gives something up", example: "They reached a compromise after a long talk." },
      { word: "perspective", pos: "noun", zh: "觀點", definition: "a particular way of viewing things", example: "Try to see it from her perspective." },
      { word: "dilemma", pos: "noun", zh: "困境；難題", definition: "a difficult choice between two options", example: "She faced a dilemma about which college to choose." },
      { word: "eradicate", pos: "verb", zh: "根除", definition: "to completely get rid of something", example: "Scientists hope to eradicate the disease." },
      { word: "credible", pos: "adj", zh: "可信的", definition: "believable, trustworthy", example: "The witness gave a credible account of events.", antonyms: [{ word: "dubious", zh: "可疑的" }] },
      { word: "diligent", pos: "adj", zh: "勤奮的", definition: "showing careful and steady effort", example: "She is a diligent student who studies every day.", synonyms: [{ word: "hardworking", zh: "勤勞的" }] },
      { word: "obsolete", pos: "adj", zh: "過時的", definition: "no longer used because something newer exists", example: "This old software is now obsolete.", synonyms: [{ word: "outdated", zh: "過時的" }] },
      { word: "advocate", pos: "verb / noun", zh: "提倡（者）；主張（者）", definition: "to publicly support an idea, or a person who does", example: "She is a strong advocate for animal rights." },
      { word: "coincide", pos: "verb", zh: "巧合；同時發生", definition: "to happen at the same time by chance", example: "Her birthday happens to coincide with the festival." },
      { word: "bear in mind", pos: "phrase", zh: "記住；謹記", definition: "to remember and consider something", example: "Bear in mind that the deadline is Friday." },
      { word: "on the verge of", pos: "phrase", zh: "瀕臨；快要", definition: "very close to doing or experiencing something", example: "The company was on the verge of bankruptcy." },
      { word: "come to terms with", pos: "phrase", zh: "接受（困難的事）", definition: "to accept something difficult", example: "It took him years to come to terms with the loss." },
    ],
    expert: [
      { word: "ubiquitous", pos: "adj", zh: "無所不在的", definition: "found everywhere", example: "Smartphones have become ubiquitous in daily life." },
      { word: "meticulous", pos: "adj", zh: "一絲不苟的", definition: "very careful and precise", example: "The scientist kept meticulous notes." },
      { word: "resilience", pos: "noun", zh: "韌性；復原力", definition: "the ability to recover from difficulty", example: "Her resilience helped her recover from the setback." },
      { word: "eloquent", pos: "adj", zh: "雄辯的；有說服力的", definition: "fluent and persuasive in speaking", example: "He gave an eloquent argument for the proposal." },
      { word: "paradox", pos: "noun", zh: "悖論", definition: "a statement that seems contradictory but may be true", example: "It's a paradox that saving time often takes longer." },
      { word: "hypothesis", pos: "noun", zh: "假設", definition: "an idea proposed as a starting point for investigation", example: "Scientists tested their hypothesis with an experiment." },
      { word: "discern", pos: "verb", zh: "辨別", definition: "to recognise or understand something clearly", example: "It was hard to discern his true intentions." },
      { word: "plausible", pos: "adj", zh: "似乎合理的", definition: "seeming reasonable or probable", example: "Her explanation sounded plausible.", antonyms: [{ word: "implausible", zh: "難以置信的" }] },
      { word: "arbitrary", pos: "adj", zh: "隨意的；武斷的", definition: "based on random choice rather than reason", example: "The deadline seemed completely arbitrary." },
      { word: "autonomy", pos: "noun", zh: "自主權", definition: "the ability to act independently", example: "Teenagers often seek more autonomy from their parents." },
      { word: "ephemeral", pos: "adj", zh: "短暫的", definition: "lasting for a very short time", example: "Fame can be ephemeral.", antonyms: [{ word: "permanent", zh: "永久的" }] },
      { word: "juxtapose", pos: "verb", zh: "並置；對比", definition: "to place two things side by side for comparison", example: "The film juxtaposes wealth and poverty." },
      { word: "pragmatic", pos: "adj", zh: "務實的", definition: "dealing with things sensibly and practically", example: "She took a pragmatic approach to the problem.", antonyms: [{ word: "idealistic", zh: "理想主義的" }] },
      { word: "ambivalent", pos: "adj", zh: "矛盾的；猶豫不決的", definition: "having mixed feelings about something", example: "He felt ambivalent about moving abroad." },
      { word: "scrutinise", pos: "verb", zh: "仔細審查", definition: "to examine something very carefully", example: "Auditors scrutinised the company's accounts.", synonyms: [{ word: "examine", zh: "審查" }] },
      { word: "quintessential", pos: "adj", zh: "典型的；最典型的", definition: "representing the most perfect example of something", example: "This dish is the quintessential comfort food." },
      { word: "circumvent", pos: "verb", zh: "迴避；規避", definition: "to find a way around a rule or difficulty", example: "They found a way to circumvent the regulation." },
      { word: "in light of", pos: "phrase", zh: "鑑於；考慮到", definition: "considering something", example: "In light of the weather, the event was postponed." },
      { word: "for the sake of", pos: "phrase", zh: "為了…的緣故", definition: "in order to help or please", example: "He stayed calm for the sake of the team." },
      { word: "at the expense of", pos: "phrase", zh: "以…為代價", definition: "causing harm to something in order to achieve something else", example: "He succeeded at the expense of his health." },
    ],
  };
})();
