// Vocabulary Builder — 40 items per tier (mostly single words, a few common
// phrases tagged pos:"phrase"), each with English word, part of speech,
// Traditional Chinese translation, a simple definition, and an example
// sentence. Some items also carry `synonyms`/`antonyms` ({word, zh} pairs)
// for the tap-to-explore related-words feature.
window.App = window.App || {};
window.App.Content = window.App.Content || {};

(function () {
  window.App.Content.VOCABULARY_ITEMS = {
    easy: [
      { word: "gigantic", pos: "adj", zh: "巨大的", definition: "extremely large", example: "The gigantic whale swam past our boat." },
      { word: "delighted", pos: "adj", zh: "非常高興的", definition: "very pleased", example: "She was delighted with her birthday gift." },
      { word: "curious", pos: "adj", zh: "好奇的", definition: "eager to know or learn something", example: "The curious cat explored every room." },
      { word: "ancient", pos: "adj", zh: "古老的", definition: "very old, from long ago", example: "We visited some ancient ruins in Rome.", antonyms: [{ word: "modern", zh: "現代的" }] },
      { word: "brave", pos: "adj", zh: "勇敢的", definition: "showing courage", example: "The brave firefighter rescued the kitten.", antonyms: [{ word: "afraid", zh: "害怕的" }] },
      { word: "wander", pos: "verb", zh: "漫遊；閒逛", definition: "to walk around without a clear direction", example: "We wandered through the old town." },
      { word: "vanish", pos: "verb", zh: "消失", definition: "to disappear suddenly", example: "The magician made the coin vanish.", antonyms: [{ word: "appear", zh: "出現" }] },
      { word: "journey", pos: "noun", zh: "旅程", definition: "a trip from one place to another", example: "Their journey across the country took five days." },
      { word: "treasure", pos: "noun", zh: "寶藏", definition: "a collection of valuable things", example: "The pirates buried their treasure on the island." },
      { word: "narrow", pos: "adj", zh: "狹窄的", definition: "having a small width", example: "The narrow path led up the mountain.", synonyms: [{ word: "thin", zh: "薄的" }], antonyms: [{ word: "wide", zh: "寬闊的" }] },
      { word: "polite", pos: "adj", zh: "有禮貌的", definition: "having good manners", example: "It's polite to say thank you.", antonyms: [{ word: "rude", zh: "無禮的" }] },
      { word: "arrive", pos: "verb", zh: "到達", definition: "to reach a place", example: "We arrived at the station on time.", synonyms: [{ word: "reach", zh: "到達" }], antonyms: [{ word: "depart", zh: "離開" }] },
      { word: "borrow", pos: "verb", zh: "借（入）", definition: "to take something and return it later", example: "Can I borrow your pencil?", antonyms: [{ word: "lend", zh: "借出" }] },
      { word: "silent", pos: "adj", zh: "安靜的；沉默的", definition: "making no sound", example: "The library was completely silent.", synonyms: [{ word: "quiet", zh: "安靜的" }], antonyms: [{ word: "noisy", zh: "吵鬧的" }] },
      { word: "message", pos: "noun", zh: "訊息", definition: "a short piece of information sent to someone", example: "She left a message on his phone." },
      { word: "protect", pos: "verb", zh: "保護", definition: "to keep someone or something safe", example: "A helmet protects your head.", synonyms: [{ word: "defend", zh: "保衛" }] },
      { word: "give up", pos: "phrase", zh: "放棄", definition: "to stop trying", example: "Don't give up on your dreams." },
      { word: "look forward to", pos: "phrase", zh: "期待", definition: "to feel excited about something that will happen", example: "I look forward to the holidays." },
      { word: "in the end", pos: "phrase", zh: "最終；到頭來", definition: "eventually, after everything", example: "In the end, they decided to stay home." },
      { word: "enormous", pos: "adj", zh: "巨大的", definition: "very big in size", example: "They live in an enormous house." },
      { word: "accomplish", pos: "verb", zh: "完成；達成", definition: "to succeed in doing something", example: "She accomplished all her goals this year.", synonyms: [{ word: "achieve", zh: "達到" }] },
      { word: "outstanding", pos: "adj", zh: "出色的；傑出的", definition: "extremely good", example: "His outstanding performance won him first prize." },
      { word: "accurate", pos: "adj", zh: "準確的", definition: "correct and exact", example: "Please give me an accurate answer.", antonyms: [{ word: "inaccurate", zh: "不準確的" }] },
      { word: "rapid", pos: "adj", zh: "快速的", definition: "happening very quickly", example: "The city has seen rapid growth in recent years.", synonyms: [{ word: "fast", zh: "快的" }] },
      { word: "rescue", pos: "verb", zh: "拯救；救援", definition: "to save someone from danger", example: "Firefighters rescued the family from the burning building." },
      { word: "scarce", pos: "adj", zh: "稀少的；不足的", definition: "not enough; hard to find", example: "Clean water was scarce during the drought.", antonyms: [{ word: "plentiful", zh: "豐富的" }] },
      { word: "sturdy", pos: "adj", zh: "堅固的", definition: "strong and solidly built", example: "The old bridge is still sturdy after 100 years." },
      { word: "survive", pos: "verb", zh: "生存；倖存", definition: "to continue to live despite difficulty", example: "Few animals can survive in such cold weather." },
      { word: "tradition", pos: "noun", zh: "傳統", definition: "a custom passed down through generations", example: "Making dumplings is a family tradition." },
      { word: "warning", pos: "noun", zh: "警告", definition: "a signal that tells you about danger", example: "The teacher gave a warning before the fire drill." },
      { word: "companion", pos: "noun", zh: "同伴", definition: "a friend who spends time with you", example: "The dog was her loyal companion on every walk." },
      { word: "familiar", pos: "adj", zh: "熟悉的", definition: "well known to you", example: "The song sounded familiar, but she couldn't remember its name.", antonyms: [{ word: "unfamiliar", zh: "陌生的" }] },
      { word: "frequent", pos: "adj", zh: "頻繁的", definition: "happening often", example: "He is a frequent visitor to the museum." },
      { word: "harsh", pos: "adj", zh: "嚴厲的；惡劣的", definition: "unpleasantly rough or severe", example: "The desert has a harsh climate.", antonyms: [{ word: "gentle", zh: "溫和的" }] },
      { word: "heroic", pos: "adj", zh: "英勇的", definition: "showing great courage", example: "The lifeguard's heroic rescue saved three swimmers." },
      { word: "hostile", pos: "adj", zh: "敵對的", definition: "unfriendly and aggressive", example: "The two countries had a hostile relationship for years.", antonyms: [{ word: "friendly", zh: "友善的" }] },
      { word: "identical", pos: "adj", zh: "完全相同的", definition: "exactly the same", example: "The twins wore identical outfits.", synonyms: [{ word: "same", zh: "相同的" }] },
      { word: "look after", pos: "phrase", zh: "照顧", definition: "to take care of someone or something", example: "Can you look after my cat this weekend?" },
      { word: "find out", pos: "phrase", zh: "發現；查明", definition: "to discover information", example: "Let's find out what time the museum opens." },
      { word: "get along with", pos: "phrase", zh: "與…相處融洽", definition: "to have a friendly relationship with someone", example: "She gets along with everyone in her class." },
    ],
    medium: [
      { word: "reluctant", pos: "adj", zh: "不情願的", definition: "unwilling to do something", example: "He was reluctant to try the spicy food.", antonyms: [{ word: "eager", zh: "渴望的" }] },
      { word: "persuade", pos: "verb", zh: "說服", definition: "to convince someone to do something", example: "She persuaded her parents to get a dog." },
      { word: "exhausted", pos: "adj", zh: "精疲力盡的", definition: "extremely tired", example: "After the race, the runners were exhausted.", synonyms: [{ word: "tired", zh: "疲倦的" }] },
      { word: "generous", pos: "adj", zh: "慷慨的", definition: "willing to give freely", example: "He was generous and shared his lunch.", antonyms: [{ word: "selfish", zh: "自私的" }] },
      { word: "hesitate", pos: "verb", zh: "猶豫", definition: "to pause because you are unsure", example: "Don't hesitate to ask for help." },
      { word: "astonish", pos: "verb", zh: "使震驚；使驚訝", definition: "to surprise someone greatly", example: "The magic trick astonished the audience.", synonyms: [{ word: "amaze", zh: "使驚奇" }] },
      { word: "resourceful", pos: "adj", zh: "足智多謀的", definition: "good at finding quick, clever solutions", example: "The resourceful team fixed the robot with tape." },
      { word: "anxious", pos: "adj", zh: "焦慮的", definition: "worried or nervous", example: "She felt anxious before the exam.", antonyms: [{ word: "calm", zh: "冷靜的" }] },
      { word: "achievement", pos: "noun", zh: "成就", definition: "something accomplished successfully", example: "Winning the competition was a huge achievement." },
      { word: "determination", pos: "noun", zh: "決心", definition: "firmness of purpose", example: "Her determination helped her finish the marathon." },
      { word: "confident", pos: "adj", zh: "自信的", definition: "feeling sure about your abilities", example: "She felt confident before the exam.", antonyms: [{ word: "nervous", zh: "緊張的" }] },
      { word: "collapse", pos: "verb", zh: "倒塌；崩潰", definition: "to fall down suddenly", example: "The old bridge collapsed during the storm." },
      { word: "isolate", pos: "verb", zh: "隔離；孤立", definition: "to separate something from others", example: "The scientists isolated the virus for study." },
      { word: "abundant", pos: "adj", zh: "豐富的", definition: "existing in large quantities", example: "Fresh water is abundant in this region.", antonyms: [{ word: "scarce", zh: "稀少的" }] },
      { word: "clumsy", pos: "adj", zh: "笨拙的", definition: "moving in an awkward way, likely to drop things", example: "He's a bit clumsy in the kitchen.", antonyms: [{ word: "graceful", zh: "優雅的" }] },
      { word: "sincere", pos: "adj", zh: "真誠的", definition: "honest and genuine", example: "He gave a sincere apology.", synonyms: [{ word: "genuine", zh: "真誠的" }], antonyms: [{ word: "fake", zh: "虛假的" }] },
      { word: "assist", pos: "verb", zh: "協助", definition: "to help someone", example: "The nurse assisted the doctor during surgery.", synonyms: [{ word: "help", zh: "幫助" }] },
      { word: "make up your mind", pos: "phrase", zh: "下定決心", definition: "to decide something", example: "It's time to make up your mind." },
      { word: "keep an eye on", pos: "phrase", zh: "留意；照看", definition: "to watch something carefully", example: "Can you keep an eye on my bag?" },
      { word: "run out of", pos: "phrase", zh: "用完", definition: "to have no more of something", example: "We ran out of milk this morning." },
      { word: "approximate", pos: "adj", zh: "大約的", definition: "close to exact but not completely accurate", example: "The approximate cost of the trip is $500." },
      { word: "astound", pos: "verb", zh: "使震驚", definition: "to surprise someone very much", example: "The results of the experiment astounded the scientists.", synonyms: [{ word: "amaze", zh: "使驚訝" }] },
      { word: "avalanche", pos: "noun", zh: "雪崩", definition: "a large mass of snow that suddenly slides down a mountain", example: "Hikers must be careful of avalanches in winter." },
      { word: "cease", pos: "verb", zh: "停止", definition: "to stop happening or doing something", example: "The noise finally ceased after midnight.", synonyms: [{ word: "stop", zh: "停止" }] },
      { word: "compassion", pos: "noun", zh: "同情心", definition: "a strong feeling of sympathy for others", example: "She showed great compassion for the injured bird." },
      { word: "convince", pos: "verb", zh: "說服", definition: "to persuade someone that something is true", example: "He convinced his parents to let him join the trip." },
      { word: "decline", pos: "verb", zh: "拒絕；下降", definition: "to politely refuse, or to become smaller or weaker", example: "She declined the invitation because she was busy.", antonyms: [{ word: "accept", zh: "接受" }] },
      { word: "dedicate", pos: "verb", zh: "奉獻；致力於", definition: "to give a lot of time and effort to something", example: "He dedicated his life to helping others." },
      { word: "endanger", pos: "verb", zh: "危害", definition: "to put something or someone at risk of harm", example: "Pollution endangers many species of fish." },
      { word: "establish", pos: "verb", zh: "建立", definition: "to set up or create something", example: "The school was established over 50 years ago." },
      { word: "evaluate", pos: "verb", zh: "評估", definition: "to judge the quality or value of something", example: "Teachers evaluate students' work carefully." },
      { word: "exert", pos: "verb", zh: "運用；施加", definition: "to make a physical or mental effort", example: "She exerted all her energy to finish the race." },
      { word: "impressive", pos: "adj", zh: "令人印象深刻的", definition: "causing admiration because of size, skill, or quality", example: "The fireworks display was truly impressive." },
      { word: "industrious", pos: "adj", zh: "勤奮的", definition: "hardworking", example: "The industrious ants worked all summer to store food.", synonyms: [{ word: "hardworking", zh: "勤勞的" }] },
      { word: "intense", pos: "adj", zh: "強烈的", definition: "very strong or extreme", example: "The athletes trained with intense focus before the game." },
      { word: "investigate", pos: "verb", zh: "調查", definition: "to carefully examine the facts of a situation", example: "Detectives investigated the mystery for weeks." },
      { word: "apparent", pos: "adj", zh: "明顯的", definition: "clear and easy to see", example: "It was apparent that she had been crying.", synonyms: [{ word: "obvious", zh: "明顯的" }] },
      { word: "courteous", pos: "adj", zh: "有禮貌的", definition: "polite and considerate", example: "The courteous waiter helped us find a table.", antonyms: [{ word: "rude", zh: "無禮的" }] },
      { word: "crave", pos: "verb", zh: "渴望", definition: "to want something very much", example: "After the hike, they craved a cold drink." },
      { word: "dissatisfied", pos: "adj", zh: "不滿意的", definition: "not happy or pleased with something", example: "The customer was dissatisfied with the service.", antonyms: [{ word: "satisfied", zh: "滿意的" }] },
    ],
    hard: [
      { word: "inevitable", pos: "adj", zh: "不可避免的", definition: "certain to happen", example: "Change was inevitable as the city grew." },
      { word: "skeptical", pos: "adj", zh: "懷疑的", definition: "having doubts about something", example: "He was skeptical about the new plan.", antonyms: [{ word: "convinced", zh: "確信的" }] },
      { word: "articulate", pos: "adj / verb", zh: "表達清晰的；清楚表達", definition: "able to express ideas clearly", example: "She gave an articulate speech." },
      { word: "persevere", pos: "verb", zh: "堅持不懈", definition: "to continue despite difficulty", example: "He persevered through months of training." },
      { word: "ambiguous", pos: "adj", zh: "模稜兩可的", definition: "unclear or open to more than one meaning", example: "The instructions were ambiguous.", antonyms: [{ word: "clear", zh: "清晰的" }] },
      { word: "underestimate", pos: "verb", zh: "低估", definition: "to think something is smaller or less important than it is", example: "Never underestimate a determined opponent.", antonyms: [{ word: "overestimate", zh: "高估" }] },
      { word: "controversy", pos: "noun", zh: "爭議", definition: "a disagreement about something", example: "The new rule caused a lot of controversy." },
      { word: "legitimate", pos: "adj", zh: "合法的；正當的", definition: "reasonable or acceptable", example: "She had a legitimate reason for being late." },
      { word: "compromise", pos: "noun / verb", zh: "妥協", definition: "an agreement where each side gives something up", example: "They reached a compromise after a long talk." },
      { word: "perspective", pos: "noun", zh: "觀點", definition: "a particular way of viewing things", example: "Try to see it from her perspective." },
      { word: "dilemma", pos: "noun", zh: "困境；難題", definition: "a difficult choice between two options", example: "She faced a dilemma about which college to choose." },
      { word: "eradicate", pos: "verb", zh: "根除", definition: "to completely get rid of something", example: "Scientists hope to eradicate the disease." },
      { word: "credible", pos: "adj", zh: "可信的", definition: "believable, trustworthy", example: "The witness gave a credible account of events.", antonyms: [{ word: "dubious", zh: "可疑的" }] },
      { word: "diligent", pos: "adj", zh: "勤奮的", definition: "showing careful and steady effort", example: "She is a diligent student who studies every day.", synonyms: [{ word: "hardworking", zh: "勤勞的" }] },
      { word: "obsolete", pos: "adj", zh: "過時的", definition: "no longer used because something newer exists", example: "This old software is now obsolete.", synonyms: [{ word: "outdated", zh: "過時的" }] },
      { word: "advocate", pos: "verb / noun", zh: "提倡（者）；主張（者）", definition: "to publicly support an idea, or a person who does", example: "She is a strong advocate for animal rights." },
      { word: "coincide", pos: "verb", zh: "巧合；同時發生", definition: "to happen at the same time by chance", example: "Her birthday happens to coincide with the festival." },
      { word: "bear in mind", pos: "phrase", zh: "記住；謹記", definition: "to remember and consider something", example: "Bear in mind that the deadline is Friday." },
      { word: "on the verge of", pos: "phrase", zh: "瀕臨；快要", definition: "very close to doing or experiencing something", example: "The company was on the verge of bankruptcy." },
      { word: "come to terms with", pos: "phrase", zh: "接受（困難的事）", definition: "to accept something difficult", example: "It took him years to come to terms with the loss." },
      { word: "anguish", pos: "noun", zh: "極度痛苦", definition: "severe mental or physical suffering", example: "The lost hikers felt anguish as night fell." },
      { word: "arrogant", pos: "adj", zh: "傲慢的", definition: "having an exaggerated sense of one's own importance", example: "His arrogant attitude made him unpopular.", antonyms: [{ word: "humble", zh: "謙遜的" }] },
      { word: "boycott", pos: "verb / noun", zh: "抵制", definition: "to refuse to buy or use something as a form of protest", example: "Consumers boycotted the company over unfair practices." },
      { word: "chronological", pos: "adj", zh: "按時間順序的", definition: "arranged in the order in which events happened", example: "The museum displays history in chronological order." },
      { word: "civilization", pos: "noun", zh: "文明", definition: "a well-organised and developed human society", example: "Ancient Egypt was one of the world's earliest civilizations." },
      { word: "conserve", pos: "verb", zh: "節省；保育", definition: "to protect and use carefully to avoid waste", example: "We should all try to conserve water.", synonyms: [{ word: "preserve", zh: "保存" }] },
      { word: "deteriorate", pos: "verb", zh: "惡化", definition: "to become progressively worse", example: "His health began to deteriorate after the accident.", antonyms: [{ word: "improve", zh: "改善" }] },
      { word: "diminish", pos: "verb", zh: "減少；縮小", definition: "to make or become smaller or less important", example: "Her enthusiasm never diminished, even after failure.", synonyms: [{ word: "decrease", zh: "減少" }] },
      { word: "diversity", pos: "noun", zh: "多樣性", definition: "a range of different people, things, or ideas", example: "The city is known for its cultural diversity." },
      { word: "negotiate", pos: "verb", zh: "談判", definition: "to discuss something in order to reach an agreement", example: "The two companies negotiated a new contract." },
      { word: "obedient", pos: "adj", zh: "服從的；聽話的", definition: "willing to do what you are told", example: "The obedient dog sat as soon as it was told.", antonyms: [{ word: "rebellious", zh: "反叛的" }] },
      { word: "abandon", pos: "verb", zh: "拋棄；放棄", definition: "to leave something or someone completely", example: "The sailors had to abandon the sinking ship." },
      { word: "abnormal", pos: "adj", zh: "異常的", definition: "different from what is usual or expected", example: "The doctor noticed an abnormal reading on the machine.", antonyms: [{ word: "normal", zh: "正常的" }] },
      { word: "adept", pos: "adj", zh: "熟練的", definition: "very skilled at doing something", example: "She is adept at solving difficult puzzles.", synonyms: [{ word: "skilful", zh: "熟練的" }] },
      { word: "allegiance", pos: "noun", zh: "效忠；忠誠", definition: "loyalty to a person, group, or cause", example: "Soldiers pledge allegiance to their country." },
      { word: "anarchy", pos: "noun", zh: "無政府狀態；混亂", definition: "a state of disorder due to lack of authority", example: "Without any rules, the classroom descended into anarchy." },
      { word: "apathy", pos: "noun", zh: "冷漠；漠不關心", definition: "a lack of interest or concern", example: "Voter apathy led to a very low turnout.", antonyms: [{ word: "enthusiasm", zh: "熱忱" }] },
      { word: "arbitrate", pos: "verb", zh: "仲裁", definition: "to help settle a dispute between two sides", example: "A judge was asked to arbitrate the disagreement." },
      { word: "astute", pos: "adj", zh: "精明的", definition: "having good judgement and quick understanding", example: "The astute businesswoman spotted the opportunity immediately.", synonyms: [{ word: "shrewd", zh: "精明的" }] },
      { word: "audacious", pos: "adj", zh: "大膽的", definition: "showing a willingness to take bold risks", example: "The audacious plan involved sneaking past every guard." },
    ],
    expert: [
      { word: "ubiquitous", pos: "adj", zh: "無所不在的", definition: "found everywhere", example: "Smartphones have become ubiquitous in daily life." },
      { word: "meticulous", pos: "adj", zh: "一絲不苟的", definition: "very careful and precise", example: "The scientist kept meticulous notes." },
      { word: "resilience", pos: "noun", zh: "韌性；復原力", definition: "the ability to recover from difficulty", example: "Her resilience helped her recover from the setback." },
      { word: "eloquent", pos: "adj", zh: "雄辯的；有說服力的", definition: "fluent and persuasive in speaking", example: "He gave an eloquent argument for the proposal." },
      { word: "paradox", pos: "noun", zh: "悖論", definition: "a statement that seems contradictory but may be true", example: "It's a paradox that saving time often takes longer." },
      { word: "hypothesis", pos: "noun", zh: "假設", definition: "an idea proposed as a starting point for investigation", example: "Scientists tested their hypothesis with an experiment." },
      { word: "discern", pos: "verb", zh: "辨別", definition: "to recognise or understand something clearly", example: "It was hard to discern his true intentions." },
      { word: "plausible", pos: "adj", zh: "似乎合理的", definition: "seeming reasonable or probable", example: "Her explanation sounded plausible.", antonyms: [{ word: "implausible", zh: "難以置信的" }] },
      { word: "arbitrary", pos: "adj", zh: "隨意的；武斷的", definition: "based on random choice rather than reason", example: "The deadline seemed completely arbitrary." },
      { word: "autonomy", pos: "noun", zh: "自主權", definition: "the ability to act independently", example: "Teenagers often seek more autonomy from their parents." },
      { word: "ephemeral", pos: "adj", zh: "短暫的", definition: "lasting for a very short time", example: "Fame can be ephemeral.", antonyms: [{ word: "permanent", zh: "永久的" }] },
      { word: "juxtapose", pos: "verb", zh: "並置；對比", definition: "to place two things side by side for comparison", example: "The film juxtaposes wealth and poverty." },
      { word: "pragmatic", pos: "adj", zh: "務實的", definition: "dealing with things sensibly and practically", example: "She took a pragmatic approach to the problem.", antonyms: [{ word: "idealistic", zh: "理想主義的" }] },
      { word: "ambivalent", pos: "adj", zh: "矛盾的；猶豫不決的", definition: "having mixed feelings about something", example: "He felt ambivalent about moving abroad." },
      { word: "scrutinise", pos: "verb", zh: "仔細審查", definition: "to examine something very carefully", example: "Auditors scrutinised the company's accounts.", synonyms: [{ word: "examine", zh: "審查" }] },
      { word: "quintessential", pos: "adj", zh: "典型的；最典型的", definition: "representing the most perfect example of something", example: "This dish is the quintessential comfort food." },
      { word: "circumvent", pos: "verb", zh: "迴避；規避", definition: "to find a way around a rule or difficulty", example: "They found a way to circumvent the regulation." },
      { word: "in light of", pos: "phrase", zh: "鑑於；考慮到", definition: "considering something", example: "In light of the weather, the event was postponed." },
      { word: "for the sake of", pos: "phrase", zh: "為了…的緣故", definition: "in order to help or please", example: "He stayed calm for the sake of the team." },
      { word: "at the expense of", pos: "phrase", zh: "以…為代價", definition: "causing harm to something in order to achieve something else", example: "He succeeded at the expense of his health." },
      { word: "belligerent", pos: "adj", zh: "好戰的；挑釁的", definition: "hostile and aggressive", example: "His belligerent tone started an argument." },
      { word: "benign", pos: "adj", zh: "溫和無害的", definition: "gentle and harmless", example: "Thankfully, the tumour turned out to be benign.", antonyms: [{ word: "malignant", zh: "惡性的" }] },
      { word: "antagonize", pos: "verb", zh: "激怒；使敵對", definition: "to provoke hostility in someone", example: "He antagonized his classmates with rude jokes." },
      { word: "augment", pos: "verb", zh: "增加；擴大", definition: "to make something greater by adding to it", example: "The team augmented their research with new data.", synonyms: [{ word: "increase", zh: "增加" }] },
      { word: "cache", pos: "noun", zh: "儲藏處；隱藏庫", definition: "a hidden store of things", example: "The pirates buried a cache of gold coins." },
      { word: "bountiful", pos: "adj", zh: "豐富的", definition: "given or occurring in generous amounts", example: "The farmers celebrated a bountiful harvest." },
      { word: "candid", pos: "adj", zh: "坦率的", definition: "truthful and straightforward", example: "She gave a candid opinion about the film.", synonyms: [{ word: "honest", zh: "誠實的" }] },
      { word: "tenacious", pos: "adj", zh: "堅韌不拔的", definition: "holding firmly to a purpose; persistent", example: "Her tenacious spirit helped her overcome every setback." },
      { word: "ostentatious", pos: "adj", zh: "炫耀的", definition: "designed to impress others; showy", example: "The ostentatious mansion had gold-plated gates.", antonyms: [{ word: "modest", zh: "樸素的" }] },
      { word: "superfluous", pos: "adj", zh: "多餘的", definition: "more than what is necessary", example: "He removed the superfluous details from his essay.", synonyms: [{ word: "unnecessary", zh: "不必要的" }] },
      { word: "austere", pos: "adj", zh: "簡樸的；嚴峻的", definition: "plain and without luxury", example: "The monks lived an austere life with few possessions." },
      { word: "cryptic", pos: "adj", zh: "神秘難解的", definition: "mysterious or difficult to understand", example: "He left a cryptic note that no one could explain." },
      { word: "formidable", pos: "adj", zh: "令人敬畏的", definition: "inspiring fear or respect through being impressively strong", example: "The chess champion was a formidable opponent." },
      { word: "conundrum", pos: "noun", zh: "難題", definition: "a confusing and difficult problem", example: "Deciding which university to attend was a real conundrum." },
      { word: "precarious", pos: "adj", zh: "不穩定的；危險的", definition: "not securely held; likely to fall or fail", example: "The vase sat in a precarious position on the shelf.", synonyms: [{ word: "unstable", zh: "不穩定的" }] },
      { word: "obscure", pos: "adj", zh: "晦澀的；鮮為人知的", definition: "not well known, or difficult to understand", example: "The professor mentioned an obscure fact about ancient Rome.", antonyms: [{ word: "famous", zh: "著名的" }] },
      { word: "tangible", pos: "adj", zh: "實在的；可觸摸的", definition: "able to be touched or clearly real", example: "The project finally showed tangible results.", antonyms: [{ word: "intangible", zh: "無形的" }] },
      { word: "innate", pos: "adj", zh: "與生俱來的", definition: "existing from birth; natural", example: "She has an innate talent for music." },
      { word: "cynical", pos: "adj", zh: "憤世嫉俗的", definition: "believing that people are motivated mainly by self-interest", example: "He became cynical after being let down so many times." },
      { word: "catalyst", pos: "noun", zh: "催化劑；促成因素", definition: "something that causes a change or event to happen", example: "The new law acted as a catalyst for social change." },
    ],
  };
})();
